/*
 * JS for areYouSure generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function areYouSure_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileworkarea_4': 'areYouSure_mobileworkarea_4',
        'eoLogo': 'areYouSure_eoLogo',
        'mobileworkarea_2': 'areYouSure_mobileworkarea_2',
        'mobilelabel_5': 'areYouSure_mobilelabel_5',
        'spacer_6': 'areYouSure_spacer_6',
        'mobilelabel_7': 'areYouSure_mobilelabel_7',
        'mobilegrid_8': 'areYouSure_mobilegrid_8',
        'mobilegridcell_9': 'areYouSure_mobilegridcell_9',
        'yesButton': 'areYouSure_yesButton',
        'mobilegridcell_10': 'areYouSure_mobilegridcell_10',
        'mobilegridcell_13': 'areYouSure_mobilegridcell_13',
        'mobilegridcell_14': 'areYouSure_mobilegridcell_14',
        'noButton': 'areYouSure_noButton',
        'mobileworkarea_3': 'areYouSure_mobileworkarea_3'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["areYouSure_submitWrongDoc_onsuccess_mapping_0"] = {
        "homeScreen": "areYouSure",
        "directions": []
    };
    Apperyio.mappings["areYouSure_submitWrongDoc_onbeforesend_mapping_0"] = {
        "homeScreen": "areYouSure",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "submitWrongDoc",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['data']['pathParams']['docID']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.submitWrongDoc = Apperyio.datasources.submitWrongDoc = new Apperyio.DataSource(eoDocsService_submitDoc_docID, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["areYouSure_submitWrongDoc_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["areYouSure_submitWrongDoc_onsuccess_mapping_0"]);
            Apperyio.navigateTo('listDocuments', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'areYouSure';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var areYouSure_onLoad = function() {
        areYouSure_elementsExtraJS();
        areYouSure_deviceEvents();
        areYouSure_windowEvents();
        areYouSure_elementsEvents();
    };
    // screen window events
    function areYouSure_windowEvents() {
        $('#areYouSure').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function areYouSure_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    Apperyio.navigateTo('documentDetails', {
                        reverse: false
                    });
                },
            });
        });
    };
    // screen elements extra js
    function areYouSure_elementsExtraJS() {
        // screen (areYouSure) extra code
    };
    // screen elements handler
    function areYouSure_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#areYouSure_mobilecontainer [name="yesButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        submitWrongDoc.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#areYouSure_mobilecontainer [name="yesButton"]');
        $(document).off("click", '#areYouSure_mobilecontainer [name="noButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('documentDetails', {
                        reverse: false
                    });
                }
            },
        }, '#areYouSure_mobilecontainer [name="noButton"]');
    };
    $(document).off("pagebeforeshow", "#areYouSure").on("pagebeforeshow", "#areYouSure", function(event, ui) {
        Apperyio.CurrentScreen = "areYouSure";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    areYouSure_onLoad();
};
$(document).off("pagecreate", "#areYouSure").on("pagecreate", "#areYouSure", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    areYouSure_js();
});