/*
 * JS for createNewDocumentDialog generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function createNewDocumentDialog_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileworkarea_4': 'createNewDocumentDialog_mobileworkarea_4',
        'eoLogo': 'createNewDocumentDialog_eoLogo',
        'mobileworkarea_2': 'createNewDocumentDialog_mobileworkarea_2',
        'chooseDocumentTypeLabel': 'createNewDocumentDialog_chooseDocumentTypeLabel',
        'documentTypeChooser': 'createNewDocumentDialog_documentTypeChooser',
        'documentTypeChooser-0': 'createNewDocumentDialog_documentTypeChooser-0',
        'spacer_8': 'createNewDocumentDialog_spacer_8',
        'enterSubjectLabel': 'createNewDocumentDialog_enterSubjectLabel',
        'docSubjectInput': 'createNewDocumentDialog_docSubjectInput',
        'mobileworkarea_3': 'createNewDocumentDialog_mobileworkarea_3',
        'submitButton': 'createNewDocumentDialog_submitButton'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["createNewDocumentDialog_documentTypeChooser_onchange_mapping_0"] = {
        "homeScreen": "createNewDocumentDialog",
        "directions": [
            {
                "from_name": "createNewDocumentDialog",
                "from_type": "UI",
                "to_name": "createDocument",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['documentTypeChooser:selectedMenuItem']",
                        "target_transformation": function(value) {
                            var temp = Apperyio.storage.docTypes.get();
                            var temp2 = temp.find(function(post, index) {
                                if (post.id == value)
                                    return true;
                            });
                            Apperyio.storage.selectedDocType.set(temp2);
                        },
                        "target": "$['documenttype_id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["createNewDocumentDialog_documentTypeChooser_onchange_mapping_1"] = {
        "homeScreen": "createNewDocumentDialog",
        "directions": [
            {
                "from_name": "selectedDocType",
                "from_type": "LOCAL_STORAGE",
                "to_name": "createNewDocumentDialog",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['name']",
                        "target_transformation": function(value, element) {
                            // var today = new Date();
                            // var date = (today.getFullYear()+'-'+(today.getMonth()+1)+'-'+(today.getDate()));
                            let date = new Date().toISOString().slice(0, 10);
                            return value + " [" + date + "]";
                        },
                        "target": "$['docSubjectInput:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["createNewDocumentDialog_getDocTypes_onsuccess_mapping_0"] = {
        "homeScreen": "createNewDocumentDialog",
        "directions": [
            {
                "from_name": "getDocTypes",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "createNewDocumentDialog",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['data']['response'][i]",
                        "target": "$['documentTypeChooser-0']"
                    },
                    {
                        "source": "$['data']['response'][i]['id']",
                        "target": "$['documentTypeChooser-0:value']"
                    },
                    {
                        "source": "$['data']['response'][i]['name']",
                        "target": "$['documentTypeChooser-0:label']"
                    }
                ]
            },
            {
                "from_name": "getDocTypes",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "docTypes",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][i]['id']",
                        "target": "$[i]['id']"
                    },
                    {
                        "source": "$['data']['response'][i]['name']",
                        "target": "$[i]['name']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["createNewDocumentDialog_getDocTypes_onbeforesend_mapping_0"] = {
        "homeScreen": "createNewDocumentDialog",
        "directions": [
            {
                "to_name": "getDocTypes",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["createNewDocumentDialog_createDoc_onsuccess_mapping_0"] = {
        "homeScreen": "createNewDocumentDialog",
        "directions": [
            {
                "from_name": "createDoc",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocID",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['id']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "createDoc",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['id']",
                        "target": "$['docID']"
                    },
                    {
                        "source": "$['data']['response'][0]['document_time']",
                        "target": "$['doctime']"
                    },
                    {
                        "source": "$['data']['response'][0]",
                        "target": "$"
                    },
                    {
                        "source": "$['data']['response'][0]['name']",
                        "target": "$['docname']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["createNewDocumentDialog_createDoc_onbeforesend_mapping_0"] = {
        "homeScreen": "createNewDocumentDialog",
        "directions": [
            {
                "from_name": "createNewDocumentDialog",
                "from_type": "UI",
                "to_name": "createDoc",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['documentTypeChooser:selectedMenuItem']",
                        "target": "$['data']['queryParams']['typeID']"
                    },
                    {
                        "source": "$['docSubjectInput:text']",
                        "target": "$['data']['queryParams']['name']"
                    }
                ]
            },
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "createDoc",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['id']",
                        "target": "$['data']['queryParams']['userID']"
                    },
                    {
                        "source": "$['domainID']",
                        "target": "$['data']['queryParams']['domainID']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.getDocTypes = Apperyio.datasources.getDocTypes = new Apperyio.DataSource(getPushDocTypes, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["createNewDocumentDialog_getDocTypes_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["createNewDocumentDialog_getDocTypes_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.createDoc = Apperyio.datasources.createDoc = new Apperyio.DataSource(insertDoc, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["createNewDocumentDialog_createDoc_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["createNewDocumentDialog_createDoc_onsuccess_mapping_0"]);
            Apperyio.navigateTo('newDocumentDetails', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'createNewDocumentDialog';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var createNewDocumentDialog_onLoad = function() {
        createNewDocumentDialog_elementsExtraJS();
        createNewDocumentDialog_deviceEvents();
        createNewDocumentDialog_windowEvents();
        createNewDocumentDialog_elementsEvents();
    };
    // screen window events
    function createNewDocumentDialog_windowEvents() {
        $('#createNewDocumentDialog').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#createNewDocumentDialog').on({
            pageshow: function(event) {
                try {
                    getDocTypes.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        });
    };
    // device events
    function createNewDocumentDialog_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    closePopup();
                },
            });
        });
    };
    // screen elements extra js
    function createNewDocumentDialog_elementsExtraJS() {
        // screen (createNewDocumentDialog) extra code
        /* documentTypeChooser */
        $("#createNewDocumentDialog_documentTypeChooser").parent().find("a.ui-btn").attr("tabindex", "1");
    };
    // screen elements handler
    function createNewDocumentDialog_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("change", '#createNewDocumentDialog_mobilecontainer [name="documentTypeChooser"]').on({
            change: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["createNewDocumentDialog_documentTypeChooser_onchange_mapping_0"]);
                Apperyio.processMappingAction(Apperyio.mappings["createNewDocumentDialog_documentTypeChooser_onchange_mapping_1"]);
            },
        }, '#createNewDocumentDialog_mobilecontainer [name="documentTypeChooser"]');
        $(document).off("click", '#createNewDocumentDialog_mobilefooter [name="submitButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        createDoc.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#createNewDocumentDialog_mobilefooter [name="submitButton"]');
    };
    $(document).off("pagebeforeshow", "#createNewDocumentDialog").on("pagebeforeshow", "#createNewDocumentDialog", function(event, ui) {
        Apperyio.CurrentScreen = "createNewDocumentDialog";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    createNewDocumentDialog_onLoad();
};
$(document).off("pagecreate", "#createNewDocumentDialog").on("pagecreate", "#createNewDocumentDialog", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    createNewDocumentDialog_js();
});