/*
 * JS for documentListDialog generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function documentListDialog_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'eoLogo': 'documentListDialog_eoLogo',
        'mobilegrid_51': 'documentListDialog_mobilegrid_51',
        'mobilegridcell_52': 'documentListDialog_mobilegridcell_52',
        'docLineShowButton': 'documentListDialog_docLineShowButton',
        'mobilegridcell_53': 'documentListDialog_mobilegridcell_53',
        'mobilegridcell_56': 'documentListDialog_mobilegridcell_56',
        'reqLineShowButton': 'documentListDialog_reqLineShowButton',
        'productListLineList': 'documentListDialog_productListLineList',
        'mobilelistitem_6': 'documentListDialog_mobilelistitem_6',
        'mobilelistitembutton_7': 'documentListDialog_mobilelistitembutton_7',
        'mobilecollapsblock_12': 'documentListDialog_mobilecollapsblock_12',
        'mobilecollapsblockheader_13': 'documentListDialog_mobilecollapsblockheader_13',
        'mobilelabel_61': 'documentListDialog_mobilelabel_61',
        'productNameDocLineLabel': 'documentListDialog_productNameDocLineLabel',
        'mobilecollapsblockcontent_14': 'documentListDialog_mobilecollapsblockcontent_14',
        'mobilegrid_16': 'documentListDialog_mobilegrid_16',
        'mobilegridcell_17': 'documentListDialog_mobilegridcell_17',
        'productBarcodeLabel': 'documentListDialog_productBarcodeLabel',
        'mobilegridcell_18': 'documentListDialog_mobilegridcell_18',
        'productBarcodeLabelShow': 'documentListDialog_productBarcodeLabelShow',
        'mobilegridcell_19': 'documentListDialog_mobilegridcell_19',
        'requestQuantityLabel': 'documentListDialog_requestQuantityLabel',
        'mobilegridcell_20': 'documentListDialog_mobilegridcell_20',
        'requestQuantityLabelShow': 'documentListDialog_requestQuantityLabelShow',
        'mobilegridcell_21': 'documentListDialog_mobilegridcell_21',
        'scanQuantityLabel': 'documentListDialog_scanQuantityLabel',
        'mobilegridcell_22': 'documentListDialog_mobilegridcell_22',
        'scanQuantityLabelShow': 'documentListDialog_scanQuantityLabelShow',
        'mobilegridcell_23': 'documentListDialog_mobilegridcell_23',
        'qrCodeLabel': 'documentListDialog_qrCodeLabel',
        'mobilegridcell_24': 'documentListDialog_mobilegridcell_24',
        'qrCodeLabelShow': 'documentListDialog_qrCodeLabelShow',
        'productReqLineList': 'documentListDialog_productReqLineList',
        'mobilelistitem_73': 'documentListDialog_mobilelistitem_73',
        'mobilelabel_79': 'documentListDialog_mobilelabel_79',
        'mobilelistitembutton_74': 'documentListDialog_mobilelistitembutton_74',
        'mobilegrid_82': 'documentListDialog_mobilegrid_82',
        'mobilegridcell_83': 'documentListDialog_mobilegridcell_83',
        'productNameReqLineLabel': 'documentListDialog_productNameReqLineLabel',
        'mobilegridcell_84': 'documentListDialog_mobilegridcell_84',
        'mobilegridcell_85': 'documentListDialog_mobilegridcell_85',
        'reqQtyReqLineLabel': 'documentListDialog_reqQtyReqLineLabel',
        'mobilegridcell_86': 'documentListDialog_mobilegridcell_86',
        'reqQtyReqLineShowLabel': 'documentListDialog_reqQtyReqLineShowLabel',
        'mobilegridcell_90': 'documentListDialog_mobilegridcell_90',
        'reqQtyRemainingReqLineLabel': 'documentListDialog_reqQtyRemainingReqLineLabel',
        'mobilegridcell_91': 'documentListDialog_mobilegridcell_91',
        'reqQtyRemainingReqLineShowLabel': 'documentListDialog_reqQtyRemainingReqLineShowLabel'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["documentListDialog_getAllDocLines_clone_1_onsuccess_mapping_0"] = {
        "homeScreen": "documentListDialog",
        "directions": [
            {
                "from_name": "getAllDocLines_clone_1",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentListDialog",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['data']['response'][i]",
                        "target_transformation": function(value, element) {
                            element.on("click", function() {
                                Apperyio.storage.selectedDocumentDetails.set(value);
                                Apperyio.storage.editMode.set(true)
                                Apperyio.storage.inputQty.set(value.productscanquantity);
                            })
                        },
                        "target": "$['mobilelistitem_6']"
                    },
                    {
                        "source": "$['data']['response'][i]['productbarcode']",
                        "target": "$['mobilelistitem_6']['productBarcodeLabelShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['requestQuantityLabel:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target": "$['mobilelistitem_6']['requestQuantityLabelShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['requestQuantityLabelShow:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productscanquantity']",
                        "target": "$['mobilelistitem_6']['scanQuantityLabelShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(value.productrequestquantity == value.productscanquantity || value.productrequestquantity == null || value.productrequestquantity == 0 ? "green" : value.productscanquantity == 0 ? "red" : "yellow");
                            if (value.productrequestquantity != value.productscanquantity && value.productrequestquantity != null && value.productrequestquantity != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            return value.productname;
                        },
                        "target": "$['mobilelistitem_6']['productNameDocLineLabel:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productscanquantity']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null') ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['scanQuantityLabelShow:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productbarcode']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['productBarcodeLabelShow:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productbarcode']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['productBarcodeLabel:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['qrcode']",
                        "target": "$['mobilelistitem_6']['qrCodeLabelShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['qrcode']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['qrCodeLabel:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['qrcode']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['qrCodeLabelShow:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentListDialog_getAllDocLines_clone_1_onbeforesend_mapping_0"] = {
        "homeScreen": "documentListDialog",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "getAllDocLines_clone_1",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['data']['pathParams']['id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentListDialog_getAllReqLines_clone_1_onsuccess_mapping_0"] = {
        "homeScreen": "documentListDialog",
        "directions": [
            {
                "from_name": "getAllReqLines_clone_1",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentListDialog",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body'][i]",
                        "target": "$['mobilelistitem_73']"
                    },
                    {
                        "source": "$['body'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(
                                value.quantityremaining == value.productscanquantity || value.quantityremaining == null || value.quantityremaining == 0 ? "green" : value.productrequestquantity == value.quantityremaining ? "red" : "yellow");
                            if (value.quantityremaining != value.productscanquantity && value.quantityremaining != null && value.quantityremaining != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            return value.productname;
                        },
                        "target": "$['mobilelistitem_73']['productNameReqLineLabel:text']"
                    },
                    {
                        "source": "$['body'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(
                                value.quantityremaining == value.productscanquantity || value.quantityremaining == null || value.quantityremaining == 0 ? "green" : value.productrequestquantity == value.quantityremaining ? "red" : "yellow");
                            if (value.quantityremaining != value.productscanquantity && value.quantityremaining != null && value.quantityremaining != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            return value.quantityremaining;
                        },
                        "target": "$['mobilelistitem_73']['reqQtyRemainingReqLineShowLabel:text']"
                    },
                    {
                        "source": "$['body'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(
                                value.quantityremaining == value.productscanquantity || value.quantityremaining == null || value.quantityremaining == 0 ? "green" : value.productrequestquantity == value.quantityremaining ? "red" : "yellow");
                            if (value.quantityremaining != value.productscanquantity && value.quantityremaining != null && value.quantityremaining != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            return "Cantitate ceruta"
                        },
                        "target": "$['mobilelistitem_73']['reqQtyReqLineLabel:text']"
                    },
                    {
                        "source": "$['body'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(
                                value.quantityremaining == value.productscanquantity || value.quantityremaining == null || value.quantityremaining == 0 ? "green" : value.productrequestquantity == value.quantityremaining ? "red" : "yellow");
                            if (value.quantityremaining != value.productscanquantity && value.quantityremaining != null && value.quantityremaining != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            return value.productrequestquantity;
                        },
                        "target": "$['mobilelistitem_73']['reqQtyReqLineShowLabel:text']"
                    },
                    {
                        "source": "$['body'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(
                                value.quantityremaining == value.productscanquantity || value.quantityremaining == null || value.quantityremaining == 0 ? "green" : value.productrequestquantity == value.quantityremaining ? "red" : "yellow");
                            if (value.quantityremaining != value.productscanquantity && value.quantityremaining != null && value.quantityremaining != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            return "Cantitate de scanat"
                        },
                        "target": "$['mobilelistitem_73']['reqQtyRemainingReqLineLabel:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentListDialog_getAllReqLines_clone_1_onbeforesend_mapping_0"] = {
        "homeScreen": "documentListDialog",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "getAllReqLines_clone_1",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['id']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.getAllDocLines_clone_1 = Apperyio.datasources.getAllDocLines_clone_1 = new Apperyio.DataSource(eoDocsServiceDetailsGet, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentListDialog_getAllDocLines_clone_1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentListDialog_getAllDocLines_clone_1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.getAllReqLines_clone_1 = Apperyio.datasources.getAllReqLines_clone_1 = new Apperyio.DataSource(eoStockScanAPI_eoDocsService_getDocRequestLines__id__get, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentListDialog_getAllReqLines_clone_1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentListDialog_getAllReqLines_clone_1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'documentListDialog';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var documentListDialog_onLoad = function() {
        documentListDialog_elementsExtraJS();
        try {
            getAllReqLines_clone_1.execute({});
        } catch (e) {
            console.error(e);
            hideSpinner();
        };
        try {
            getAllDocLines_clone_1.execute({});
        } catch (e) {
            console.error(e);
            hideSpinner();
        };
        documentListDialog_deviceEvents();
        documentListDialog_windowEvents();
        documentListDialog_elementsEvents();
    };
    // screen window events
    function documentListDialog_windowEvents() {
        $('#documentListDialog').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function documentListDialog_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    Apperyio.navigateTo('documentDetails', {
                        reverse: false
                    });
                },
            });
        });
    };
    // screen elements extra js
    function documentListDialog_elementsExtraJS() {
        // screen (documentListDialog) extra code
        /* productListLineList */
        listView = $("#documentListDialog_productListLineList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#documentListDialog_productListLineList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_6 */
        /* mobilecollapsblock_12 */
        $("#documentListDialog_mobilecollapsblock_12 .ui-collapsible-heading-toggle").attr("tabindex", "2");
        /* productReqLineList */
        listView = $("#documentListDialog_productReqLineList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#documentListDialog_productReqLineList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_73 */
    };
    // screen elements handler
    function documentListDialog_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#documentListDialog_mobileheader [name="docLineShowButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    toggle('documentListDialog_productListLineList', 'mob', 'true');
                    toggle('documentListDialog_productReqLineList', 'mob', 'false');
                }
            },
        }, '#documentListDialog_mobileheader [name="docLineShowButton"]');
        $(document).off("click", '#documentListDialog_mobileheader [name="reqLineShowButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    toggle('documentListDialog_productListLineList', 'mob', 'false');
                    toggle('documentListDialog_productReqLineList', 'mob', 'true');
                }
            },
        }, '#documentListDialog_mobileheader [name="reqLineShowButton"]');
        $(document).off("click", '#documentListDialog_mobilecontainer [name="mobilelistitem_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('scanDocDetailsFoundDialog', {
                        transition: 'pop'
                    });
                }
            },
        }, '#documentListDialog_mobilecontainer [name="mobilelistitem_6"]');
    };
    $(document).off("pagebeforeshow", "#documentListDialog").on("pagebeforeshow", "#documentListDialog", function(event, ui) {
        Apperyio.CurrentScreen = "documentListDialog";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    documentListDialog_onLoad();
};
$(document).off("pagecreate", "#documentListDialog").on("pagecreate", "#documentListDialog", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    documentListDialog_js();
});