/*
 * JS for documentListPage generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function documentListPage_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'eoLogo': 'documentListPage_eoLogo',
        'mobilelabel_60': 'documentListPage_mobilelabel_60',
        'listLineList': 'documentListPage_listLineList',
        'mobilelistitem_27': 'documentListPage_mobilelistitem_27',
        'mobilelistitembutton_28': 'documentListPage_mobilelistitembutton_28',
        'mobilecollapsblock_33': 'documentListPage_mobilecollapsblock_33',
        'mobilecollapsblockheader_34': 'documentListPage_mobilecollapsblockheader_34',
        'productNameDocLineLabel': 'documentListPage_productNameDocLineLabel',
        'mobilecollapsblockcontent_35': 'documentListPage_mobilecollapsblockcontent_35',
        'mobilegrid_37': 'documentListPage_mobilegrid_37',
        'mobilegridcell_38': 'documentListPage_mobilegridcell_38',
        'productBarcodeLabel': 'documentListPage_productBarcodeLabel',
        'mobilegridcell_39': 'documentListPage_mobilegridcell_39',
        'productBarcodeLabelShow': 'documentListPage_productBarcodeLabelShow',
        'mobilegridcell_40': 'documentListPage_mobilegridcell_40',
        'requestQuantityLabel': 'documentListPage_requestQuantityLabel',
        'mobilegridcell_41': 'documentListPage_mobilegridcell_41',
        'requestQuantityLabelShow': 'documentListPage_requestQuantityLabelShow',
        'mobilegridcell_42': 'documentListPage_mobilegridcell_42',
        'scanQuantityLabel': 'documentListPage_scanQuantityLabel',
        'mobilegridcell_43': 'documentListPage_mobilegridcell_43',
        'scanQuantityLabelShow': 'documentListPage_scanQuantityLabelShow',
        'mobilegridcell_44': 'documentListPage_mobilegridcell_44',
        'qrCodeLabel': 'documentListPage_qrCodeLabel',
        'mobilegridcell_45': 'documentListPage_mobilegridcell_45',
        'qrCodeLabelShow': 'documentListPage_qrCodeLabelShow',
        'reqLineList': 'documentListPage_reqLineList',
        'mobilelistitem_6': 'documentListPage_mobilelistitem_6',
        'mobilelistitembutton_7': 'documentListPage_mobilelistitembutton_7',
        'mobilegrid_19': 'documentListPage_mobilegrid_19',
        'mobilegridcell_20': 'documentListPage_mobilegridcell_20',
        'productNameReqLineLabel': 'documentListPage_productNameReqLineLabel',
        'mobilegridcell_21': 'documentListPage_mobilegridcell_21',
        'mobilegridcell_22': 'documentListPage_mobilegridcell_22',
        'reqQtyReqLineLabel': 'documentListPage_reqQtyReqLineLabel',
        'mobilegridcell_23': 'documentListPage_mobilegridcell_23',
        'reqQtyReqLineShowLabel': 'documentListPage_reqQtyReqLineShowLabel',
        'mobilegridcell_24': 'documentListPage_mobilegridcell_24',
        'reqQtyRemainingReqLineLabel': 'documentListPage_reqQtyRemainingReqLineLabel',
        'mobilegridcell_25': 'documentListPage_mobilegridcell_25',
        'reqQtyRemainingReqLineShowLabel': 'documentListPage_reqQtyRemainingReqLineShowLabel',
        'mobilegrid_12': 'documentListPage_mobilegrid_12',
        'mobilegridcell_13': 'documentListPage_mobilegridcell_13',
        'docLineShowButton': 'documentListPage_docLineShowButton',
        'mobilegridcell_14': 'documentListPage_mobilegridcell_14',
        'reqLineShowButton': 'documentListPage_reqLineShowButton'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["documentListPage_docLineShowButton_onclick_mapping_2"] = {
        "homeScreen": "documentListPage",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "documentListPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target_transformation": function(value, element) {
                            return "Linii scanate"
                        },
                        "target": "$['mobilelabel_60:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentListPage_reqLineShowButton_onclick_mapping_2"] = {
        "homeScreen": "documentListPage",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "documentListPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target_transformation": function(value, element) {
                            return "Linii cerute"
                        },
                        "target": "$['mobilelabel_60:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentListPage_getAllDocLines_clone_2_onsuccess_mapping_0"] = {
        "homeScreen": "documentListPage",
        "directions": [
            {
                "from_name": "getAllDocLines_clone_2",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentListPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['data']['response'][i]",
                        "target_transformation": function(value, element) {
                            element.on("click", function() {
                                Apperyio.storage.selectedDocumentDetails.set(value);
                                Apperyio.storage.editMode.set(true)
                                Apperyio.storage.inputQty.set(value.productscanquantity);
                            })
                        },
                        "target": "$['mobilelistitem_27']"
                    },
                    {
                        "source": "$['data']['response'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(value.productrequestquantity == value.productscanquantity || value.productrequestquantity == null || value.productrequestquantity == 0 ? "green" : value.productscanquantity == 0 ? "red" : "yellow");
                            if (value.productrequestquantity != value.productscanquantity && value.productrequestquantity != null && value.productrequestquantity != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            return value.productname;
                        },
                        "target": "$['mobilelistitem_27']['productNameDocLineLabel:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productbarcode']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_27']['productBarcodeLabel:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productbarcode']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_27']['productBarcodeLabelShow:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productbarcode']",
                        "target": "$['mobilelistitem_27']['productBarcodeLabelShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_27']['requestQuantityLabelShow:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_27']['requestQuantityLabel:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target": "$['mobilelistitem_27']['requestQuantityLabelShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productscanquantity']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_27']['scanQuantityLabel:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productscanquantity']",
                        "target": "$['mobilelistitem_27']['scanQuantityLabelShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productscanquantity']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_27']['scanQuantityLabelShow:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['qrcode']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_27']['qrCodeLabel:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['qrcode']",
                        "target": "$['mobilelistitem_27']['qrCodeLabelShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['qrcode']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 'null' && value != 0) ? true : false;
                        },
                        "target": "$['mobilelistitem_27']['qrCodeLabelShow:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentListPage_getAllDocLines_clone_2_onbeforesend_mapping_0"] = {
        "homeScreen": "documentListPage",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "getAllDocLines_clone_2",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['data']['pathParams']['id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentListPage_getAllReqLines_clone_2_onsuccess_mapping_0"] = {
        "homeScreen": "documentListPage",
        "directions": [
            {
                "from_name": "getAllReqLines_clone_2",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentListPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(
                                value.quantityremaining == value.productscanquantity || value.quantityremaining == null || (Math.round((value.quantityremaining + Number.EPSILON) * 100) / 100) == 0 ? "green" : value.productrequestquantity == value.quantityremaining ? "red" : "yellow");
                            if (value.quantityremaining != value.productscanquantity && value.quantityremaining != null && value.quantityremaining != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            return value.productname;
                        },
                        "target": "$['mobilelistitem_6']['productNameReqLineLabel:text']"
                    },
                    {
                        "source": "$['body'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(
                                value.quantityremaining == value.productscanquantity || value.quantityremaining == null || (Math.round((value.quantityremaining + Number.EPSILON) * 100) / 100) == 0 ? "green" : value.productrequestquantity == value.quantityremaining ? "red" : "yellow");
                            if (value.quantityremaining != value.productscanquantity && value.quantityremaining != null && value.quantityremaining != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            return "Cantitate ceruta"
                        },
                        "target": "$['mobilelistitem_6']['reqQtyReqLineLabel:text']"
                    },
                    {
                        "source": "$['body'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(
                                value.quantityremaining == value.productscanquantity || value.quantityremaining == null || (Math.round((value.quantityremaining + Number.EPSILON) * 100) / 100) == 0 ? "green" : value.productrequestquantity == value.quantityremaining ? "red" : "yellow");
                            if (value.quantityremaining != value.productscanquantity && value.quantityremaining != null && value.quantityremaining != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            return value.productrequestquantity;
                        },
                        "target": "$['mobilelistitem_6']['reqQtyReqLineShowLabel:text']"
                    },
                    {
                        "source": "$['body'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(
                                value.quantityremaining == value.productscanquantity || value.quantityremaining == null || (Math.round((value.quantityremaining + Number.EPSILON) * 100) / 100) == 0 ? "green" : value.productrequestquantity == value.quantityremaining ? "red" : "yellow");
                            if (value.quantityremaining != value.productscanquantity && value.quantityremaining != null && value.quantityremaining != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            return "Cantitate de scanat";
                        },
                        "target": "$['mobilelistitem_6']['reqQtyRemainingReqLineLabel:text']"
                    },
                    {
                        "source": "$['body'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(
                                value.quantityremaining == value.productscanquantity || value.quantityremaining == null || (Math.round((value.quantityremaining + Number.EPSILON) * 100) / 100) == 0 ? "green" : value.productrequestquantity == value.quantityremaining ? "red" : "yellow");
                            if (value.quantityremaining != value.productscanquantity && value.quantityremaining != null && value.quantityremaining != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            //return value.quantityremaining
                            return Math.round((value.quantityremaining + Number.EPSILON) * 100) / 100;
                        },
                        "target": "$['mobilelistitem_6']['reqQtyRemainingReqLineShowLabel:text']"
                    },
                    {
                        "source": "$['body'][i]",
                        "target": "$['mobilelistitem_6']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentListPage_getAllReqLines_clone_2_onbeforesend_mapping_0"] = {
        "homeScreen": "documentListPage",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "getAllReqLines_clone_2",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['id']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.getAllDocLines_clone_2 = Apperyio.datasources.getAllDocLines_clone_2 = new Apperyio.DataSource(eoDocsServiceDetailsGet, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentListPage_getAllDocLines_clone_2_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentListPage_getAllDocLines_clone_2_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.getAllReqLines_clone_2 = Apperyio.datasources.getAllReqLines_clone_2 = new Apperyio.DataSource(eoStockScanAPI_eoDocsService_getDocRequestLines__id__get, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentListPage_getAllReqLines_clone_2_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentListPage_getAllReqLines_clone_2_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'documentListPage';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var documentListPage_onLoad = function() {
        documentListPage_elementsExtraJS();
        try {
            getAllReqLines_clone_2.execute({});
        } catch (e) {
            console.error(e);
            hideSpinner();
        };
        try {
            getAllDocLines_clone_2.execute({});
        } catch (e) {
            console.error(e);
            hideSpinner();
        };
        documentListPage_deviceEvents();
        documentListPage_windowEvents();
        documentListPage_elementsEvents();
    };
    // screen window events
    function documentListPage_windowEvents() {
        $('#documentListPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#documentListPage').on({
            pageshow: function(event) {
                try {
                    $a.storage["scanModeOn"].update("$", "false")
                } catch (e) {
                    console.error(e)
                };
            },
        });
    };
    // device events
    function documentListPage_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    Apperyio.navigateTo('documentDetails', {
                        reverse: false
                    });
                },
            });
        });
    };
    // screen elements extra js
    function documentListPage_elementsExtraJS() {
        // screen (documentListPage) extra code
        /* listLineList */
        listView = $("#documentListPage_listLineList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#documentListPage_listLineList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_27 */
        /* mobilecollapsblock_33 */
        $("#documentListPage_mobilecollapsblock_33 .ui-collapsible-heading-toggle").attr("tabindex", "5");
        /* reqLineList */
        listView = $("#documentListPage_reqLineList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#documentListPage_reqLineList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_6 */
    };
    // screen elements handler
    function documentListPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#documentListPage_mobilecontainer [name="mobilelistitem_27"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('scanDocDetailsFoundDialog', {
                        transition: 'pop'
                    });
                }
            },
        }, '#documentListPage_mobilecontainer [name="mobilelistitem_27"]');
        $(document).off("click", '#documentListPage_mobilefooter [name="docLineShowButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    toggle('documentListPage_reqLineList', 'mob', 'false');
                    toggle('documentListPage_listLineList', 'mob', 'true');
                    Apperyio.processMappingAction(Apperyio.mappings["documentListPage_docLineShowButton_onclick_mapping_2"]);
                }
            },
        }, '#documentListPage_mobilefooter [name="docLineShowButton"]');
        $(document).off("click", '#documentListPage_mobilefooter [name="reqLineShowButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    toggle('documentListPage_listLineList', 'mob', 'false');
                    toggle('documentListPage_reqLineList', 'mob', 'true');
                    Apperyio.processMappingAction(Apperyio.mappings["documentListPage_reqLineShowButton_onclick_mapping_2"]);
                }
            },
        }, '#documentListPage_mobilefooter [name="reqLineShowButton"]');
    };
    $(document).off("pagebeforeshow", "#documentListPage").on("pagebeforeshow", "#documentListPage", function(event, ui) {
        Apperyio.CurrentScreen = "documentListPage";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    documentListPage_onLoad();
};
$(document).off("pagecreate", "#documentListPage").on("pagecreate", "#documentListPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    documentListPage_js();
});