/*
 * JS for documentDetails generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function documentDetails_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileworkarea_4': 'documentDetails_mobileworkarea_4',
        'eoLogo': 'documentDetails_eoLogo',
        'mobileworkarea_2': 'documentDetails_mobileworkarea_2',
        'docNameLabel': 'documentDetails_docNameLabel',
        'docTimeLabel': 'documentDetails_docTimeLabel',
        'spacer_42': 'documentDetails_spacer_42',
        'vizualizeListDocPopup': 'documentDetails_vizualizeListDocPopup',
        'docVizList': 'documentDetails_docVizList',
        'mobilelistitem_45': 'documentDetails_mobilelistitem_45',
        'mobilelistitembutton_46': 'documentDetails_mobilelistitembutton_46',
        'mobilecollapsblock_51': 'documentDetails_mobilecollapsblock_51',
        'mobilecollapsblockheader_52': 'documentDetails_mobilecollapsblockheader_52',
        'productNameLabelPopup': 'documentDetails_productNameLabelPopup',
        'mobilecollapsblockcontent_53': 'documentDetails_mobilecollapsblockcontent_53',
        'mobilegrid_55': 'documentDetails_mobilegrid_55',
        'mobilegridcell_56': 'documentDetails_mobilegridcell_56',
        'productBarcodeLabelPopup': 'documentDetails_productBarcodeLabelPopup',
        'mobilegridcell_57': 'documentDetails_mobilegridcell_57',
        'productBarcodeLabelPopupShow': 'documentDetails_productBarcodeLabelPopupShow',
        'mobilegridcell_58': 'documentDetails_mobilegridcell_58',
        'requestQuantityLabelPopup': 'documentDetails_requestQuantityLabelPopup',
        'mobilegridcell_59': 'documentDetails_mobilegridcell_59',
        'requestQuantityLabelPopupShow': 'documentDetails_requestQuantityLabelPopupShow',
        'mobilegridcell_60': 'documentDetails_mobilegridcell_60',
        'scanQuantityLabelPopup': 'documentDetails_scanQuantityLabelPopup',
        'mobilegridcell_61': 'documentDetails_mobilegridcell_61',
        'scanQuantityLabelPopupShow': 'documentDetails_scanQuantityLabelPopupShow',
        'scanSearchBarDocDetails': 'documentDetails_scanSearchBarDocDetails',
        'scanProductButton': 'documentDetails_scanProductButton',
        'spacer_40': 'documentDetails_spacer_40',
        'submitDocumentButton': 'documentDetails_submitDocumentButton',
        'spacer_41': 'documentDetails_spacer_41',
        'vizualizeButton': 'documentDetails_vizualizeButton',
        'documentDetailsList': 'documentDetails_documentDetailsList',
        'documentDetailsListItem': 'documentDetails_documentDetailsListItem',
        'mobilecollapsblock_24': 'documentDetails_mobilecollapsblock_24',
        'mobilecollapsblockheader_25': 'documentDetails_mobilecollapsblockheader_25',
        'productNameLabel': 'documentDetails_productNameLabel',
        'mobilecollapsblockcontent_26': 'documentDetails_mobilecollapsblockcontent_26',
        'mobilegrid_27': 'documentDetails_mobilegrid_27',
        'mobilegridcell_28': 'documentDetails_mobilegridcell_28',
        'productBarcodeLabel': 'documentDetails_productBarcodeLabel',
        'mobilegridcell_29': 'documentDetails_mobilegridcell_29',
        'productBarcodeShowLabel': 'documentDetails_productBarcodeShowLabel',
        'mobilegridcell_30': 'documentDetails_mobilegridcell_30',
        'requestQuantityLabel': 'documentDetails_requestQuantityLabel',
        'mobilegridcell_31': 'documentDetails_mobilegridcell_31',
        'requestQuantityShowLabel': 'documentDetails_requestQuantityShowLabel',
        'mobilegridcell_34': 'documentDetails_mobilegridcell_34',
        'scanQuantityLabel': 'documentDetails_scanQuantityLabel',
        'mobilegridcell_35': 'documentDetails_mobilegridcell_35',
        'scanQuantityShowLabel': 'documentDetails_scanQuantityShowLabel',
        'mobilelistitembutton_12': 'documentDetails_mobilelistitembutton_12',
        'mobileworkarea_3': 'documentDetails_mobileworkarea_3'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["documentDetails_documentDetails_onpageshow_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['docID']"
                    }
                ]
            },
            {
                "from_name": "enteredUserInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "documentDetails",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['scanWithScanner']",
                        "target_transformation": function(value, element) {
                            if (value == "on") {
                                return true
                            } else {
                                return false
                            }
                        },
                        "target": "$['scanSearchBarDocDetails:visible']"
                    },
                    {
                        "source": "$['scanWithScanner']",
                        "target_transformation": function(value, element) {
                            if (value === "on") {
                                return false
                            } else {
                                return true
                            }
                        },
                        "target": "$['scanProductButton:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_scanSearchBarDocDetails_onchange_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "documentDetails",
                "from_type": "UI",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['scanSearchBarDocDetails:text']",
                        "target": "$['productbarcode']"
                    }
                ]
            },
            {
                "from_name": "documentDetails",
                "from_type": "UI",
                "to_name": "scannedValue",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['scanSearchBarDocDetails:text']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_docDetailsGetService_onerror_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "documentDetails",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['name']",
                        "target_transformation": function(value, element) {
                            return "DB Service Error"
                        },
                        "target": "$['docNameLabel:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_docDetailsGetService_onsuccess_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "docDetailsGetService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentDetails",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['data']['response'][i]",
                        "target_transformation": function(value, element) {
                            element.on("click", function() {
                                Apperyio.storage.selectedDocumentDetails.set(value);
                            })
                        },
                        "target": "$['documentDetailsListItem']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target": "$['documentDetailsListItem']['requestQuantityShowLabel:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productscanquantity']",
                        "target": "$['documentDetailsListItem']['scanQuantityShowLabel:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productbarcode']",
                        "target": "$['documentDetailsListItem']['productBarcodeShowLabel:text']"
                    },
                    {
                        "source": "$['data']['response'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(value.productrequestquantity == value.productscanquantity || value.productrequestquantity == null || value.productrequestquantity == 0 ? "green" : value.productscanquantity == 0 ? "red" : "yellow");
                            if (value.productrequestquantity != value.productscanquantity && value.productrequestquantity != null && value.productrequestquantity != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            return value.productname;
                        },
                        "target": "$['documentDetailsListItem']['productNameLabel:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return value != null ? true : false;
                        },
                        "target": "$['documentDetailsListItem']['requestQuantityShowLabel:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return value != null ? true : false;
                        },
                        "target": "$['documentDetailsListItem']['requestQuantityLabel:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]",
                        "target_transformation": function(value, element) {
                            element.on("click", function() {
                                Apperyio.storage.selectedDocumentDetails.set(value);
                            })
                        },
                        "target": "$['mobilelistitem_45']"
                    },
                    {
                        "source": "$['data']['response'][i]",
                        "target_transformation": function(value, element) {
                            $(element).addClass(value.productrequestquantity == value.productscanquantity || value.productrequestquantity == null || value.productrequestquantity == 0 ? "green" : value.productscanquantity == 0 ? "red" : "yellow");
                            if (value.productrequestquantity != value.productscanquantity && value.productrequestquantity != null && value.productrequestquantity != 0) {
                                Apperyio.storage.documentMismatch.set(true);
                            }
                            return value.productname;
                        },
                        "target": "$['mobilelistitem_45']['productNameLabelPopup:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productbarcode']",
                        "target": "$['mobilelistitem_45']['productBarcodeLabelPopupShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return value != null ? true : false;
                        },
                        "target": "$['mobilelistitem_45']['requestQuantityLabelPopup:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target": "$['mobilelistitem_45']['requestQuantityLabelPopupShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return value != null ? true : false;
                        },
                        "target": "$['mobilelistitem_45']['requestQuantityLabelPopupShow:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productscanquantity']",
                        "target": "$['mobilelistitem_45']['scanQuantityLabelPopupShow:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_docDetailsGetService_onbeforesend_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "docDetailsGetService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['data']['pathParams']['id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_submitDoc_onsuccess_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": []
    };
    Apperyio.mappings["documentDetails_submitDoc_onbeforesend_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "submitDoc",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['data']['pathParams']['docID']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_barcodeReadrToDocLineScans_onsuccess_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "barcodeReadrToDocLineScans",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['text']",
                        "target": "$['productbarcode']"
                    }
                ]
            },
            {
                "from_name": "barcodeReadrToDocLineScans",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "scannedValue",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['text']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "barcodeReadrToDocLineScans",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentMismatch",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['cancelled']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_barcodeReadrToDocLineScans_onbeforesend_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": []
    };
    Apperyio.mappings["documentDetails_getDocLineByBarcodeScan_onsuccess_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "getDocLineByBarcodeScan",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['id']",
                        "target": "$['doclineid']"
                    },
                    {
                        "source": "$['data']['response'][0]['document_id']",
                        "target": "$['docID']"
                    },
                    {
                        "source": "$['data']['response'][0]['product_name']",
                        "target": "$['productname']"
                    },
                    {
                        "source": "$['data']['response'][0]['scan_qty']",
                        "target": "$['productscanquantity']"
                    },
                    {
                        "source": "$['data']['response'][0]['req_qty']",
                        "target": "$['productrequestquantity']"
                    }
                ]
            },
            {
                "from_name": "getDocLineByBarcodeScan",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "scanQty",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['scan_qty']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "getDocLineByBarcodeScan",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "editMode",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['scan_qty']",
                        "target_transformation": function(value) {
                            return false
                        },
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_getDocLineByBarcodeScan_onbeforesend_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "getDocLineByBarcodeScan",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['data']['pathParams']['docID']"
                    }
                ]
            },
            {
                "from_name": "selectedDocumentDetails",
                "from_type": "LOCAL_STORAGE",
                "to_name": "getDocLineByBarcodeScan",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['productbarcode']",
                        "target": "$['data']['pathParams']['barcode']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_productBarcodeValidationService_onsuccess_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "productBarcodeValidationService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['id']",
                        "target": "$['productListLineID']"
                    },
                    {
                        "source": "$['data']['response'][0]['product_name']",
                        "target": "$['productname']"
                    }
                ]
            },
            {
                "from_name": "productBarcodeValidationService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentMismatch",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['id']",
                        "target_transformation": function(value) {
                            return value != undefined ? false : true;
                        },
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['docID']"
                    }
                ]
            },
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocID",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_productBarcodeValidationService_onbeforesend_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "selectedDocumentDetails",
                "from_type": "LOCAL_STORAGE",
                "to_name": "productBarcodeValidationService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['productbarcode']",
                        "target": "$['data']['pathParams']['barcode']"
                    }
                ]
            },
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "productBarcodeValidationService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['domainID']",
                        "target": "$['data']['queryParams']['domainID']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_getCurrentDocService_onsuccess_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "getCurrentDocService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentDetails",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['data']['document_time']",
                        "target": "$['docTimeLabel:text']"
                    },
                    {
                        "source": "$['data']['name']",
                        "target": "$['docNameLabel:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_getCurrentDocService_onbeforesend_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "getCurrentDocService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['data']['id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_productRequestValidation_onsuccess_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['docID']"
                    }
                ]
            },
            {
                "from_name": "productRequestValidation",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['id']",
                        "target": "$['productListLineID']"
                    },
                    {
                        "source": "$['body']['barcode']",
                        "target": "$['productbarcode']"
                    },
                    {
                        "source": "$['body']['product_name']",
                        "target": "$['productname']"
                    },
                    {
                        "source": "$['body']['productrequestquantity']",
                        "target": "$['productrequestquantity']"
                    },
                    {
                        "source": "$['body']['quantityremaining']",
                        "target": "$['productRemainingQty']"
                    }
                ]
            },
            {
                "from_name": "productRequestValidation",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentMismatch",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['id']",
                        "target_transformation": function(value) {
                            return (value != undefined && value != null) ? false : true;
                        },
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "scanQty",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['productscanquantity']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_productRequestValidation_onbeforesend_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "productRequestValidation",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['domainID']",
                        "target": "$['parameters']['domainID']"
                    }
                ]
            },
            {
                "from_name": "productCode",
                "from_type": "LOCAL_STORAGE",
                "to_name": "productRequestValidation",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['productCode']"
                    }
                ]
            },
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "productRequestValidation",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['docID']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_insertProductToDocLineReq_onsuccess_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "insertProductToDocLineReq",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body'][0]['id']",
                        "target": "$['doclineid']"
                    },
                    {
                        "source": "$['body'][0]['barcode']",
                        "target": "$['productbarcode']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_insertProductToDocLineReq_onbeforesend_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "enteredUserInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "insertProductToDocLineReq",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['id']",
                        "target_transformation": function(value) {
                            return 1;
                        },
                        "target": "$['parameters']['write_uid']"
                    }
                ]
            },
            {
                "from_name": "selectedDocumentDetails",
                "from_type": "LOCAL_STORAGE",
                "to_name": "insertProductToDocLineReq",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['productListLineID']",
                        "target": "$['parameters']['productlistline_id']"
                    },
                    {
                        "source": "$['productbarcode']",
                        "target": "$['parameters']['barcode']"
                    },
                    {
                        "source": "$['productscanquantity']",
                        "target_transformation": function(value) {
                            return 0
                        },
                        "target": "$['parameters']['scan_qty']"
                    },
                    {
                        "source": "$['docID']",
                        "target": "$['parameters']['document_id']"
                    },
                    {
                        "source": "$['productname']",
                        "target": "$['parameters']['product_name']"
                    }
                ]
            },
            {
                "from_name": "scannedValue",
                "from_type": "LOCAL_STORAGE",
                "to_name": "insertProductToDocLineReq",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['qr_code']"
                    }
                ]
            },
            {
                "to_name": "insertProductToDocLineReq",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "target_transformation": function(value) {
                            return 0;
                        },
                        "target": "$['parameters']['req_qty']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_getReqDocLineByBarcodeScan_onsuccess_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['docID']"
                    }
                ]
            },
            {
                "from_name": "getReqDocLineByBarcodeScan",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['productrequestquantity']",
                        "target": "$['productrequestquantity']"
                    },
                    {
                        "source": "$['body']['quantityremaining']",
                        "target": "$['productRemainingQty']"
                    },
                    {
                        "source": "$['body']['productlistlineid']",
                        "target": "$['productListLineID']"
                    },
                    {
                        "source": "$['body']['product_name']",
                        "target": "$['productname']"
                    },
                    {
                        "source": "$['body']['product_code']",
                        "target": "$['productCode']"
                    }
                ]
            },
            {
                "from_name": "getReqDocLineByBarcodeScan",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "productCode",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['product_code']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "getReqDocLineByBarcodeScan",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "scannedValue",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['requestlineid']",
                        "target_transformation": function(value) {
                            return null;
                        },
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_getReqDocLineByBarcodeScan_onbeforesend_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "selectedDocumentDetails",
                "from_type": "LOCAL_STORAGE",
                "to_name": "getReqDocLineByBarcodeScan",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['productbarcode']",
                        "target": "$['parameters']['barcode']"
                    }
                ]
            },
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "getReqDocLineByBarcodeScan",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_processDoc_onsuccess_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": []
    };
    Apperyio.mappings["documentDetails_processDoc_onbeforesend_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "processDoc",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_getCurrentDocService_1_onsuccess_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "getCurrentDocService_1",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentDetails",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body']['name']",
                        "target": "$['docNameLabel:text']"
                    },
                    {
                        "source": "$['body']['document_time']",
                        "target": "$['docTimeLabel:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["documentDetails_getCurrentDocService_1_onbeforesend_mapping_0"] = {
        "homeScreen": "documentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "getCurrentDocService_1",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['id']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.docDetailsGetService = Apperyio.datasources.docDetailsGetService = new Apperyio.DataSource(eoDocsServiceDetailsGet, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_docDetailsGetService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_docDetailsGetService_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_docDetailsGetService_onerror_mapping_0"]);
        }
    });
    window.submitDoc = Apperyio.datasources.submitDoc = new Apperyio.DataSource(eoDocsService_submitDoc_docID, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_submitDoc_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_submitDoc_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.barcodeReadrToDocLineScans = Apperyio.datasources.barcodeReadrToDocLineScans = new Apperyio.DataSource(BarcodeService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_barcodeReadrToDocLineScans_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_barcodeReadrToDocLineScans_onsuccess_mapping_0"]);
            if (Apperyio.storage.documentMismatch.get() == true) {
                Apperyio.storage.scanModeOn.set(false)
                return;
            }
            var barcode = Apperyio.storage.scannedValue.get();
            if (barcode[0] == "[") {
                var temp = "";
                var i = 1;
                for (i; i < barcode.length; i++) {
                    if (barcode[i] != "]") {
                        temp += barcode[i]
                    } else {
                        Apperyio.storage.productCode.set(temp)
                        break;
                    }
                }
                if (barcode[++i] == "[") {
                    temp = "";
                    i++;
                    for (i; i < barcode.length; i++) {
                        if (barcode[i] != "]") {
                            temp += barcode[i]
                        } else {
                            Apperyio.storage.scanQty.set(temp)
                            break;
                        }
                    }
                }
                productRequestValidation.execute({});
            } else {
                getReqDocLineByBarcodeScan.execute({});
            }
            ;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.getDocLineByBarcodeScan = Apperyio.datasources.getDocLineByBarcodeScan = new Apperyio.DataSource(getDocLineByBarcode, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_getDocLineByBarcodeScan_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_getDocLineByBarcodeScan_onsuccess_mapping_0"]);
            if (Apperyio.storage.selectedDocumentDetails.get("$['doclineid']") == undefined) {
                productBarcodeValidationService.execute({});
            } else {
                Apperyio.navigateTo('scanDocDetailsFoundDialog', {
                    transition: 'pop'
                });
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            try {
                $a.storage["scanModeOn"].update("$", "false")
            } catch (e) {
                console.error(e)
            };
        }
    });
    window.productBarcodeValidationService = Apperyio.datasources.productBarcodeValidationService = new Apperyio.DataSource(validateProductBarcode, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_productBarcodeValidationService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_productBarcodeValidationService_onsuccess_mapping_0"]);
            if (Apperyio.storage.documentMismatch.get() == true) {
                Apperyio.navigateTo('scanProductDetailsNotFoundDialog', {
                    transition: 'pop'
                });
            } else {
                Apperyio.navigateTo('scanProductDetailsNotFoundDialog_clone_1', {
                    transition: 'pop'
                });
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            Apperyio.navigateTo('scanDocDetailsNotFoundDialog', {
                transition: 'pop'
            });
        }
    });
    window.getCurrentDocService = Apperyio.datasources.getCurrentDocService = new Apperyio.DataSource(eoDocsGeneratedService_get, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_getCurrentDocService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_getCurrentDocService_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.productRequestValidation = Apperyio.datasources.productRequestValidation = new Apperyio.DataSource(eoStockScanAPI_eoDocsService_reqValidation_get, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_productRequestValidation_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_productRequestValidation_onsuccess_mapping_0"]);
            if (Apperyio.storage.documentMismatch.get() == true) {
                Apperyio.navigateTo('scanProductDetailsNotFoundDialog', {
                    transition: 'pop'
                });
            } else {
                insertProductToDocLineReq.execute({});
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            try {
                $a.storage["scanModeOn"].update("$", "false")
            } catch (e) {
                console.error(e)
            };
            Apperyio.navigateTo('scanDocDetailsNotFoundDialog', {
                transition: 'pop'
            });
        }
    });
    window.insertProductToDocLineReq = Apperyio.datasources.insertProductToDocLineReq = new Apperyio.DataSource(eoStockScanAPI_eoDocsService_insertDocLineQR_post, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_insertProductToDocLineReq_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_insertProductToDocLineReq_onsuccess_mapping_0"]);
            Apperyio.navigateTo('scanDocDetailsFoundDialog', {
                transition: 'pop'
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.getReqDocLineByBarcodeScan = Apperyio.datasources.getReqDocLineByBarcodeScan = new Apperyio.DataSource(eoStockScanAPI_eoDocsService_getRequestDocLineByBarcode_get, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_getReqDocLineByBarcodeScan_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_getReqDocLineByBarcodeScan_onsuccess_mapping_0"]);
            try {
                productRequestValidation.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            Apperyio.navigateTo('scanDocDetailsNotFoundDialog', {
                transition: 'pop'
            });
        }
    });
    window.processDoc = Apperyio.datasources.processDoc = new Apperyio.DataSource(eoStockScanAPI_eoDocsService_processDoc_put, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_processDoc_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_processDoc_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.getCurrentDocService_1 = Apperyio.datasources.getCurrentDocService_1 = new Apperyio.DataSource(eoStockScanAPI_eoDocsService_getDoc_get, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_getCurrentDocService_1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["documentDetails_getCurrentDocService_1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'documentDetails';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var documentDetails_onLoad = function() {
        documentDetails_elementsExtraJS();
        documentDetails_deviceEvents();
        documentDetails_windowEvents();
        documentDetails_elementsEvents();
    };
    // screen window events
    function documentDetails_windowEvents() {
        $('#documentDetails').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#documentDetails').on({
            pageshow: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["documentDetails_documentDetails_onpageshow_mapping_0"]);
                try {
                    getCurrentDocService_1.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
                try {
                    $a.storage["documentMismatch"].update("$", "false")
                } catch (e) {
                    console.error(e)
                };
                if (Apperyio.storage.scanModeOn.get() == "true") {
                    barcodeReadrToDocLineScans.execute({});
                } else {};
            },
        });
    };
    // device events
    function documentDetails_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    Apperyio.navigateTo('mainPage', {
                        reverse: false
                    });
                },
            });
        });
    };
    // screen elements extra js
    function documentDetails_elementsExtraJS() {
        // screen (documentDetails) extra code
        /* vizualizeListDocPopup */
        $("#documentDetails_vizualizeListDocPopup").popup("option", "positionTo", "window");
        /* docVizList */
        listView = $("#documentDetails_docVizList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#documentDetails_docVizList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_45 */
        /* mobilecollapsblock_51 */
        $("#documentDetails_mobilecollapsblock_51 .ui-collapsible-heading-toggle").attr("tabindex", "6");
        /* documentDetailsList */
        listView = $("#documentDetails_documentDetailsList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#documentDetails_documentDetailsList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* documentDetailsListItem */
        /* mobilecollapsblock_24 */
        $("#documentDetails_mobilecollapsblock_24 .ui-collapsible-heading-toggle").attr("tabindex", "3");
    };
    // screen elements handler
    function documentDetails_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#documentDetails_vizualizeListDocPopup [name="mobilelistitem_45"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('scanDocDetailsNotFoundDialog', {
                        transition: 'pop'
                    });
                }
            },
        }, '#documentDetails_vizualizeListDocPopup [name="mobilelistitem_45"]');
        $(document).off("change", '#documentDetails_mobilecontainer [name="scanSearchBarDocDetails"]').on({
            change: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["documentDetails_scanSearchBarDocDetails_onchange_mapping_0"]);
                var barcode = Apperyio.storage.scannedValue.get();
                if (barcode[0] == "[") {
                    var temp = "";
                    var i = 1;
                    for (i; i < barcode.length; i++) {
                        if (barcode[i] != "]") {
                            temp += barcode[i]
                        } else {
                            Apperyio.storage.productCode.set(temp)
                            break;
                        }
                    }
                    if (barcode[++i] == "[") {
                        temp = "";
                        i++;
                        for (i; i < barcode.length; i++) {
                            if (barcode[i] != "]") {
                                temp += barcode[i]
                            } else {
                                Apperyio.storage.scanQty.set(temp)
                                break;
                            }
                        }
                    }
                    productRequestValidation.execute({});
                } else {
                    getReqDocLineByBarcodeScan.execute({});
                }
                ;
            },
        }, '#documentDetails_mobilecontainer [name="scanSearchBarDocDetails"]');
        $(document).off("click", '#documentDetails_mobilecontainer [name="scanProductButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["scanModeOn"].update("$", "true")
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        barcodeReadrToDocLineScans.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#documentDetails_mobilecontainer [name="scanProductButton"]');
        $(document).off("click", '#documentDetails_mobilecontainer [name="submitDocumentButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    if (Apperyio.storage.documentMismatch.get() == true) {
                        Apperyio.navigateTo("areYouSure");
                    } else {
                        submitDoc.execute({});
                        Apperyio.navigateTo("listDocuments");
                    };
                }
            },
        }, '#documentDetails_mobilecontainer [name="submitDocumentButton"]');
        $(document).off("click", '#documentDetails_mobilecontainer [name="vizualizeButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('documentListPage', {
                        reverse: false
                    });
                }
            },
        }, '#documentDetails_mobilecontainer [name="vizualizeButton"]');
        $(document).off("click", '#documentDetails_mobilecontainer [name="documentDetailsListItem"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('scanDocDetailsFoundDialog', {
                        transition: 'pop'
                    });
                }
            },
        }, '#documentDetails_mobilecontainer [name="documentDetailsListItem"]');
    };
    $(document).off("pagebeforeshow", "#documentDetails").on("pagebeforeshow", "#documentDetails", function(event, ui) {
        Apperyio.CurrentScreen = "documentDetails";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    documentDetails_onLoad();
};
$(document).off("pagecreate", "#documentDetails").on("pagecreate", "#documentDetails", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    documentDetails_js();
});