/*
 * JS for loginFailed generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function loginFailed_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_5': 'loginFailed_mobilebutton_5',
        'mobileimage_4': 'loginFailed_mobileimage_4',
        'mobilelabel_3': 'loginFailed_mobilelabel_3'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["loginFailed_loginLoggingFailedService_onsuccess_mapping_0"] = {
        "homeScreen": "loginFailed",
        "directions": []
    };
    Apperyio.mappings["loginFailed_loginLoggingFailedService_onbeforesend_mapping_0"] = {
        "homeScreen": "loginFailed",
        "directions": [
            {
                "from_name": "enteredUserInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "loginLoggingFailedService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": [
                    {
                        "source": "$['username']",
                        "target": "$['data']['username_entered']"
                    }
                ]
            },
            {
                "to_name": "loginLoggingFailedService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": [
                    {
                        "target_transformation": function(value) {
                            return 0;
                        },
                        "target": "$['data']['status']"
                    },
                    {
                        "target_transformation": function(value) {
                            return 1;
                        },
                        "target": "$['data']['log_type']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.loginLoggingFailedService = Apperyio.datasources.loginLoggingFailedService = new Apperyio.DataSource(userLoggingService_create, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["loginFailed_loginLoggingFailedService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["loginFailed_loginLoggingFailedService_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'loginFailed';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var loginFailed_onLoad = function() {
        loginFailed_elementsExtraJS();
        try {
            loginLoggingFailedService.execute({});
        } catch (e) {
            console.error(e);
            hideSpinner();
        };
        loginFailed_deviceEvents();
        loginFailed_windowEvents();
        loginFailed_elementsEvents();
    };
    // screen window events
    function loginFailed_windowEvents() {
        $('#loginFailed').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function loginFailed_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    Apperyio.navigateTo('loginPage', {
                        reverse: false
                    });
                },
            });
        });
    };
    // screen elements extra js
    function loginFailed_elementsExtraJS() {
        // screen (loginFailed) extra code
    };
    // screen elements handler
    function loginFailed_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#loginFailed_mobileheader [name="mobilebutton_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('loginPage', {
                        reverse: false
                    });
                }
            },
        }, '#loginFailed_mobileheader [name="mobilebutton_5"]');
    };
    $(document).off("pagebeforeshow", "#loginFailed").on("pagebeforeshow", "#loginFailed", function(event, ui) {
        Apperyio.CurrentScreen = "loginFailed";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    loginFailed_onLoad();
};
$(document).off("pagecreate", "#loginFailed").on("pagecreate", "#loginFailed", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    loginFailed_js();
});