/*
 * JS for loginSuccess generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function loginSuccess_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage_17': 'loginSuccess_mobileimage_17',
        'mobilegrid_2': 'loginSuccess_mobilegrid_2',
        'mobilegridcell_3': 'loginSuccess_mobilegridcell_3',
        'nameLabel': 'loginSuccess_nameLabel',
        'mobilegridcell_4': 'loginSuccess_mobilegridcell_4',
        'nameShowLabel': 'loginSuccess_nameShowLabel',
        'mobilegridcell_5': 'loginSuccess_mobilegridcell_5',
        'usernameLabel': 'loginSuccess_usernameLabel',
        'mobilegridcell_6': 'loginSuccess_mobilegridcell_6',
        'usernameShowLabel': 'loginSuccess_usernameShowLabel',
        'mobilegridcell_7': 'loginSuccess_mobilegridcell_7',
        'emailLabel': 'loginSuccess_emailLabel',
        'mobilegridcell_8': 'loginSuccess_mobilegridcell_8',
        'emailShowLabel': 'loginSuccess_emailShowLabel',
        'confirmButton': 'loginSuccess_confirmButton',
        'logoutButton': 'loginSuccess_logoutButton'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["loginSuccess_loginSuccess_onpageshow_mapping_0"] = {
        "homeScreen": "loginSuccess",
        "directions": [
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "loginSuccess",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['name']",
                        "target": "$['nameShowLabel:text']"
                    },
                    {
                        "source": "$['username']",
                        "target": "$['usernameShowLabel:text']"
                    },
                    {
                        "source": "$['email']",
                        "target": "$['emailShowLabel:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["loginSuccess_userLoginSuccessLogging_onsuccess_mapping_0"] = {
        "homeScreen": "loginSuccess",
        "directions": []
    };
    Apperyio.mappings["loginSuccess_userLoginSuccessLogging_onbeforesend_mapping_0"] = {
        "homeScreen": "loginSuccess",
        "directions": [
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "userLoginSuccessLogging",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": [
                    {
                        "source": "$['id']",
                        "target": "$['data']['user_id']"
                    },
                    {
                        "source": "$['username']",
                        "target": "$['data']['username_entered']"
                    }
                ]
            },
            {
                "to_name": "userLoginSuccessLogging",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": [
                    {
                        "target_transformation": function(value) {
                            return 1;
                        },
                        "target": "$['data']['log_type']"
                    },
                    {
                        "target_transformation": function(value) {
                            return 1;
                        },
                        "target": "$['data']['status']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["loginSuccess_userLogoutLogging_onsuccess_mapping_0"] = {
        "homeScreen": "loginSuccess",
        "directions": []
    };
    Apperyio.mappings["loginSuccess_userLogoutLogging_onbeforesend_mapping_0"] = {
        "homeScreen": "loginSuccess",
        "directions": [
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "userLogoutLogging",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": [
                    {
                        "source": "$['username']",
                        "target": "$['data']['username_entered']"
                    },
                    {
                        "source": "$['id']",
                        "target": "$['data']['user_id']"
                    }
                ]
            },
            {
                "to_name": "userLogoutLogging",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": [
                    {
                        "target_transformation": function(value) {
                            return 1;
                        },
                        "target": "$['data']['status']"
                    },
                    {
                        "target_transformation": function(value) {
                            return 0;
                        },
                        "target": "$['data']['log_type']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.userLoginSuccessLogging = Apperyio.datasources.userLoginSuccessLogging = new Apperyio.DataSource(userLoggingService_create, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["loginSuccess_userLoginSuccessLogging_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["loginSuccess_userLoginSuccessLogging_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.userLogoutLogging = Apperyio.datasources.userLogoutLogging = new Apperyio.DataSource(userLoggingService_create, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["loginSuccess_userLogoutLogging_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["loginSuccess_userLogoutLogging_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'loginSuccess';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var loginSuccess_onLoad = function() {
        loginSuccess_elementsExtraJS();
        try {
            userLoginSuccessLogging.execute({});
        } catch (e) {
            console.error(e);
            hideSpinner();
        };
        loginSuccess_deviceEvents();
        loginSuccess_windowEvents();
        loginSuccess_elementsEvents();
    };
    // screen window events
    function loginSuccess_windowEvents() {
        $('#loginSuccess').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#loginSuccess').on({
            pageshow: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["loginSuccess_loginSuccess_onpageshow_mapping_0"]);
            },
        });
    };
    // device events
    function loginSuccess_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    try {
                        userLogoutLogging.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    navigator.app.exitApp();
                },
            });
        });
    };
    // screen elements extra js
    function loginSuccess_elementsExtraJS() {
        // screen (loginSuccess) extra code
    };
    // screen elements handler
    function loginSuccess_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#loginSuccess_mobilecontainer [name="confirmButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('mainPage', {
                        reverse: false
                    });
                }
            },
        }, '#loginSuccess_mobilecontainer [name="confirmButton"]');
        $(document).off("click", '#loginSuccess_mobilefooter [name="logoutButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('loginPage', {
                        reverse: false
                    });
                    try {
                        userLogoutLogging.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#loginSuccess_mobilefooter [name="logoutButton"]');
    };
    $(document).off("pagebeforeshow", "#loginSuccess").on("pagebeforeshow", "#loginSuccess", function(event, ui) {
        Apperyio.CurrentScreen = "loginSuccess";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    loginSuccess_onLoad();
};
$(document).off("pagecreate", "#loginSuccess").on("pagecreate", "#loginSuccess", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    loginSuccess_js();
});