/*
 * JS for loginPage generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function loginPage_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage_17': 'loginPage_mobileimage_17',
        'userNameInput': 'loginPage_userNameInput',
        'passwordInput': 'loginPage_passwordInput',
        'loginButton': 'loginPage_loginButton'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["loginPage_loginPage_onpageshow_mapping_1"] = {
        "homeScreen": "loginPage",
        "directions": [
            {
                "from_name": "enteredUserInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "loginPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['username']",
                        "target": "$['userNameInput:text']"
                    },
                    {
                        "source": "$['password']",
                        "target": "$['passwordInput:text']"
                    }
                ]
            },
            {
                "from_name": "enteredUserInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "enteredUserInfos",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['name']",
                        "target_transformation": function(value) {
                            return "";
                        },
                        "target": "$['name']"
                    },
                    {
                        "source": "$['email']",
                        "target_transformation": function(value) {
                            return "";
                        },
                        "target": "$['email']"
                    },
                    {
                        "source": "$['id']",
                        "target_transformation": function(value) {
                            return undefined;
                        },
                        "target": "$['id']"
                    },
                    {
                        "source": "$['domainID']",
                        "target_transformation": function(value) {
                            return undefined;
                        },
                        "target": "$['domainID']"
                    },
                    {
                        "source": "$['scanWithScanner']",
                        "target_transformation": function(value) {
                            if (value != "on") {
                                return "off";
                            }
                        },
                        "target": "$['scanWithScanner']"
                    }
                ]
            },
            {
                "from_name": "selectedDocumentDetails",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['docID']",
                        "target_transformation": function(value) {
                            return undefined;
                        },
                        "target": "$['docID']"
                    },
                    {
                        "source": "$['doclineid']",
                        "target_transformation": function(value) {
                            return undefined;
                        },
                        "target": "$['doclineid']"
                    },
                    {
                        "source": "$['productname']",
                        "target_transformation": function(value) {
                            return "";
                        },
                        "target": "$['productname']"
                    },
                    {
                        "source": "$['productbarcode']",
                        "target_transformation": function(value) {
                            return "";
                        },
                        "target": "$['productbarcode']"
                    },
                    {
                        "source": "$['productrequestquantity']",
                        "target_transformation": function(value) {
                            return null;
                        },
                        "target": "$['productrequestquantity']"
                    },
                    {
                        "source": "$['productscanquantity']",
                        "target_transformation": function(value) {
                            return null;
                        },
                        "target": "$['productscanquantity']"
                    },
                    {
                        "source": "$['docname']",
                        "target_transformation": function(value) {
                            return "";
                        },
                        "target": "$['docname']"
                    },
                    {
                        "source": "$['doctime']",
                        "target_transformation": function(value) {
                            return "";
                        },
                        "target": "$['doctime']"
                    },
                    {
                        "source": "$['docsubject']",
                        "target_transformation": function(value) {
                            return "";
                        },
                        "target": "$['docsubject']"
                    },
                    {
                        "source": "$['productListLineID']",
                        "target_transformation": function(value) {
                            return undefined;
                        },
                        "target": "$['productListLineID']"
                    },
                    {
                        "source": "$['document_type']",
                        "target_transformation": function(value) {
                            return "";
                        },
                        "target": "$['document_type']"
                    },
                    {
                        "source": "$['productQrCode']",
                        "target_transformation": function(value) {
                            return "";
                        },
                        "target": "$['productQrCode']"
                    },
                    {
                        "source": "$['productCode']",
                        "target_transformation": function(value) {
                            return "";
                        },
                        "target": "$['productCode']"
                    },
                    {
                        "source": "$['productRemainingQty']",
                        "target_transformation": function(value) {
                            return null;
                        },
                        "target": "$['productRemainingQty']"
                    }
                ]
            },
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocID",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target_transformation": function(value) {
                            return undefined;
                        },
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "scanQty",
                "from_type": "LOCAL_STORAGE",
                "to_name": "scanQty",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target_transformation": function(value) {
                            return 0;
                        },
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "inputQty",
                "from_type": "LOCAL_STORAGE",
                "to_name": "inputQty",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target_transformation": function(value) {
                            return 0;
                        },
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "editMode",
                "from_type": "LOCAL_STORAGE",
                "to_name": "editMode",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target_transformation": function(value) {
                            return false;
                        },
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["loginPage_loginVerificationService_onerror_mapping_0"] = {
        "homeScreen": "loginPage",
        "directions": [
            {
                "from_name": "loginPage",
                "from_type": "UI",
                "to_name": "enteredUserInfos",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['userNameInput:text']",
                        "target": "$['username']"
                    },
                    {
                        "source": "$['passwordInput:text']",
                        "target": "$['password']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["loginPage_loginVerificationService_onsuccess_mapping_0"] = {
        "homeScreen": "loginPage",
        "directions": [
            {
                "from_name": "loginPage",
                "from_type": "UI",
                "to_name": "enteredUserInfos",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['userNameInput:text']",
                        "target": "$['username']"
                    },
                    {
                        "source": "$['passwordInput:text']",
                        "target": "$['password']"
                    }
                ]
            },
            {
                "from_name": "loginVerificationService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "userInfos",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['username']",
                        "target": "$['username']"
                    },
                    {
                        "source": "$['data']['response'][0]['password']",
                        "target": "$['password']"
                    },
                    {
                        "source": "$['data']['response'][0]['name']",
                        "target": "$['name']"
                    },
                    {
                        "source": "$['data']['response'][0]['email']",
                        "target": "$['email']"
                    },
                    {
                        "source": "$['data']['response'][0]['id']",
                        "target": "$['id']"
                    },
                    {
                        "source": "$['data']['response'][0]['domain_id']",
                        "target": "$['domainID']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["loginPage_loginVerificationService_onbeforesend_mapping_0"] = {
        "homeScreen": "loginPage",
        "directions": [
            {
                "from_name": "loginPage",
                "from_type": "UI",
                "to_name": "loginVerificationService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": [
                    {
                        "source": "$['userNameInput:text']",
                        "target": "$['data']['pathParams']['username']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.loginVerificationService = Apperyio.datasources.loginVerificationService = new Apperyio.DataSource(eoStockScanUserLoginService_get, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["loginPage_loginVerificationService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["loginPage_loginVerificationService_onsuccess_mapping_0"]);
            var addedPassW = Apperyio.storage.enteredUserInfos.get("$['password']");
            var passW = Apperyio.storage.userInfos.get("$['password']");
            if (addedPassW.localeCompare(passW) != 0) {
                Apperyio.navigateTo("loginFailed", {});
            } else {
                Apperyio.navigateTo("mainPage", {});
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            Apperyio.processMappingAction(Apperyio.mappings["loginPage_loginVerificationService_onerror_mapping_0"]);
            Apperyio.navigateTo('loginFailed', {
                reverse: false
            });
        }
    });
    Apperyio.CurrentScreen = 'loginPage';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var loginPage_onLoad = function() {
        loginPage_elementsExtraJS();
        loginPage_deviceEvents();
        loginPage_windowEvents();
        loginPage_elementsEvents();
    };
    // screen window events
    function loginPage_windowEvents() {
        $('#loginPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#loginPage').on({
            pageshow: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["loginPage_loginPage_onpageshow_mapping_1"]);
            },
        });
    };
    // device events
    function loginPage_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    navigator.app.exitApp();
                },
            });
        });
    };
    // screen elements extra js
    function loginPage_elementsExtraJS() {
        // screen (loginPage) extra code
    };
    // screen elements handler
    function loginPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#loginPage_mobilefooter [name="loginButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        loginVerificationService.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#loginPage_mobilefooter [name="loginButton"]');
    };
    $(document).off("pagebeforeshow", "#loginPage").on("pagebeforeshow", "#loginPage", function(event, ui) {
        Apperyio.CurrentScreen = "loginPage";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    loginPage_onLoad();
};
$(document).off("pagecreate", "#loginPage").on("pagecreate", "#loginPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    loginPage_js();
});