/*
 * JS for newDocumentDetails generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function newDocumentDetails_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileworkarea_4': 'newDocumentDetails_mobileworkarea_4',
        'eoLogo': 'newDocumentDetails_eoLogo',
        'mobileworkarea_2': 'newDocumentDetails_mobileworkarea_2',
        'docNameLabel': 'newDocumentDetails_docNameLabel',
        'docTimeLabel': 'newDocumentDetails_docTimeLabel',
        'spacer_42': 'newDocumentDetails_spacer_42',
        'vizualizeDocPopup': 'newDocumentDetails_vizualizeDocPopup',
        'mobilelist_44': 'newDocumentDetails_mobilelist_44',
        'mobilelistitem_45': 'newDocumentDetails_mobilelistitem_45',
        'mobilelistitembutton_46': 'newDocumentDetails_mobilelistitembutton_46',
        'mobilecollapsblock_51': 'newDocumentDetails_mobilecollapsblock_51',
        'mobilecollapsblockheader_52': 'newDocumentDetails_mobilecollapsblockheader_52',
        'productNameLabelPopup': 'newDocumentDetails_productNameLabelPopup',
        'mobilecollapsblockcontent_53': 'newDocumentDetails_mobilecollapsblockcontent_53',
        'mobilegrid_55': 'newDocumentDetails_mobilegrid_55',
        'mobilegridcell_56': 'newDocumentDetails_mobilegridcell_56',
        'productBarcodeLabelPopup': 'newDocumentDetails_productBarcodeLabelPopup',
        'mobilegridcell_57': 'newDocumentDetails_mobilegridcell_57',
        'productBarcodeLabelPopupShow': 'newDocumentDetails_productBarcodeLabelPopupShow',
        'mobilegridcell_58': 'newDocumentDetails_mobilegridcell_58',
        'requestQuantityLabelPopup': 'newDocumentDetails_requestQuantityLabelPopup',
        'mobilegridcell_59': 'newDocumentDetails_mobilegridcell_59',
        'requestQuantityLabelPopupShow': 'newDocumentDetails_requestQuantityLabelPopupShow',
        'mobilegridcell_60': 'newDocumentDetails_mobilegridcell_60',
        'scanQuantityLabelPopup': 'newDocumentDetails_scanQuantityLabelPopup',
        'mobilegridcell_61': 'newDocumentDetails_mobilegridcell_61',
        'scanQuantityLabelPopupShow': 'newDocumentDetails_scanQuantityLabelPopupShow',
        'scanSearchBarNewDocDetails': 'newDocumentDetails_scanSearchBarNewDocDetails',
        'scanProductButton': 'newDocumentDetails_scanProductButton',
        'spacer_40': 'newDocumentDetails_spacer_40',
        'submitDocumentButton': 'newDocumentDetails_submitDocumentButton',
        'spacer_41': 'newDocumentDetails_spacer_41',
        'vizualizeButton': 'newDocumentDetails_vizualizeButton',
        'documentDetailsList': 'newDocumentDetails_documentDetailsList',
        'documentDetailsListItem': 'newDocumentDetails_documentDetailsListItem',
        'mobilecollapsblock_24': 'newDocumentDetails_mobilecollapsblock_24',
        'mobilecollapsblockheader_25': 'newDocumentDetails_mobilecollapsblockheader_25',
        'productNameLabel': 'newDocumentDetails_productNameLabel',
        'mobilecollapsblockcontent_26': 'newDocumentDetails_mobilecollapsblockcontent_26',
        'mobilegrid_27': 'newDocumentDetails_mobilegrid_27',
        'mobilegridcell_28': 'newDocumentDetails_mobilegridcell_28',
        'productBarcodeLabel': 'newDocumentDetails_productBarcodeLabel',
        'mobilegridcell_29': 'newDocumentDetails_mobilegridcell_29',
        'productBarcodeShowLabel': 'newDocumentDetails_productBarcodeShowLabel',
        'mobilegridcell_30': 'newDocumentDetails_mobilegridcell_30',
        'requestQuantityLabel': 'newDocumentDetails_requestQuantityLabel',
        'mobilegridcell_31': 'newDocumentDetails_mobilegridcell_31',
        'requestQuantityShowLabel': 'newDocumentDetails_requestQuantityShowLabel',
        'mobilegridcell_34': 'newDocumentDetails_mobilegridcell_34',
        'scanQuantityLabel': 'newDocumentDetails_scanQuantityLabel',
        'mobilegridcell_35': 'newDocumentDetails_mobilegridcell_35',
        'scanQuantityShowLabel': 'newDocumentDetails_scanQuantityShowLabel',
        'mobilelistitembutton_12': 'newDocumentDetails_mobilelistitembutton_12',
        'mobileworkarea_3': 'newDocumentDetails_mobileworkarea_3'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["newDocumentDetails_newDocumentDetails_onpageshow_mapping_2"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['docID']"
                    }
                ]
            },
            {
                "from_name": "enteredUserInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "newDocumentDetails",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['scanWithScanner']",
                        "target_transformation": function(value, element) {
                            if (value == "on") {
                                return true
                            } else {
                                return false
                            }
                        },
                        "target": "$['scanSearchBarNewDocDetails:visible']"
                    },
                    {
                        "source": "$['scanWithScanner']",
                        "target_transformation": function(value, element) {
                            if (value == "on") {
                                return false;
                            } else {
                                return true;
                            }
                        },
                        "target": "$['scanProductButton:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_scanSearchBarNewDocDetails_onchange_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "newDocumentDetails",
                "from_type": "UI",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['scanSearchBarNewDocDetails:text']",
                        "target": "$['productbarcode']"
                    }
                ]
            },
            {
                "from_name": "newDocumentDetails",
                "from_type": "UI",
                "to_name": "scannedValue",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['scanSearchBarNewDocDetails:text']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_scanSearchBarNewDocDetails_onchange_mapping_3"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "scannedValue",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['productQrCode']"
                    }
                ]
            },
            {
                "from_name": "productCode",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['productCode']"
                    }
                ]
            },
            {
                "from_name": "scanQty",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['productscanquantity']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_currentDocDetailsGetService_onerror_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "newDocumentDetails",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['name']",
                        "target_transformation": function(value, element) {
                            return "DB Service Error"
                        },
                        "target": "$['docNameLabel:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_currentDocDetailsGetService_onsuccess_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "currentDocDetailsGetService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "newDocumentDetails",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['data']['response'][i]",
                        "target_transformation": function(value, element) {
                            element.on("click", function() {
                                Apperyio.storage.selectedDocumentDetails.set(value);
                            })
                        },
                        "target": "$['documentDetailsListItem']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target": "$['documentDetailsListItem']['requestQuantityShowLabel:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productscanquantity']",
                        "target": "$['documentDetailsListItem']['scanQuantityShowLabel:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productbarcode']",
                        "target": "$['documentDetailsListItem']['productBarcodeShowLabel:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productname']",
                        "target": "$['documentDetailsListItem']['productNameLabel:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return value != null ? true : false;
                        },
                        "target": "$['documentDetailsListItem']['requestQuantityShowLabel:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return value != null ? true : false;
                        },
                        "target": "$['documentDetailsListItem']['requestQuantityLabel:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]",
                        "target_transformation": function(value, element) {
                            element.on("click", function() {
                                Apperyio.storage.selectedDocumentDetails.set(value);
                            })
                        },
                        "target": "$['mobilelistitem_45']"
                    },
                    {
                        "source": "$['data']['response'][i]['productname']",
                        "target": "$['mobilelistitem_45']['productNameLabelPopup:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productbarcode']",
                        "target": "$['mobilelistitem_45']['productBarcodeLabelPopupShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return value != null ? true : false;
                        },
                        "target": "$['mobilelistitem_45']['requestQuantityLabelPopup:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target": "$['mobilelistitem_45']['requestQuantityLabelPopupShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return value != null ? true : false;
                        },
                        "target": "$['mobilelistitem_45']['requestQuantityLabelPopupShow:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productscanquantity']",
                        "target": "$['mobilelistitem_45']['scanQuantityLabelPopupShow:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_currentDocDetailsGetService_onbeforesend_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "currentDocDetailsGetService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['data']['pathParams']['id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_submitDoc_onsuccess_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": []
    };
    Apperyio.mappings["newDocumentDetails_submitDoc_onbeforesend_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "submitDoc",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['data']['pathParams']['docID']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_barcodeReadrToDocLineScan_onsuccess_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "barcodeReadrToDocLineScan",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['text']",
                        "target": "$['productbarcode']"
                    }
                ]
            },
            {
                "from_name": "barcodeReadrToDocLineScan",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "scannedValue",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['text']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "barcodeReadrToDocLineScan",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentMismatch",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['cancelled']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_barcodeReadrToDocLineScan_onbeforesend_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": []
    };
    Apperyio.mappings["newDocumentDetails_productBarcodeValidation_onsuccess_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "productBarcodeValidation",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['id']",
                        "target": "$['productListLineID']"
                    },
                    {
                        "source": "$['data']['response'][0]['product_name']",
                        "target": "$['productname']"
                    }
                ]
            },
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['docID']"
                    }
                ]
            },
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocID",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "productBarcodeValidation",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentMismatch",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['id']",
                        "target_transformation": function(value) {
                            return value != undefined ? false : true;
                        },
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_productBarcodeValidation_onbeforesend_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "selectedDocumentDetails",
                "from_type": "LOCAL_STORAGE",
                "to_name": "productBarcodeValidation",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['productbarcode']",
                        "target": "$['data']['pathParams']['barcode']"
                    }
                ]
            },
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "productBarcodeValidation",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['domainID']",
                        "target": "$['data']['queryParams']['domainID']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_insertProductToDocLine_onerror_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "docBarcode",
                "from_type": "LOCAL_STORAGE",
                "to_name": "newDocumentDetails",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target_transformation": function(value, element) {
                            return "Insert failed"
                        },
                        "target": "$['mobileheader:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_insertProductToDocLine_onsuccess_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "insertProductToDocLine",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['id']",
                        "target": "$['doclineid']"
                    }
                ]
            },
            {
                "from_name": "insertProductToDocLine",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "scanQty",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['scan_qty']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "insertProductToDocLine",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "editMode",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['scan_qty']",
                        "target_transformation": function(value) {
                            return false
                        },
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_insertProductToDocLine_onbeforesend_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "insertProductToDocLine",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['id']",
                        "target_transformation": function(value) {
                            return 1;
                        },
                        "target": "$['data']['queryParams']['write_uid']"
                    }
                ]
            },
            {
                "from_name": "selectedDocumentDetails",
                "from_type": "LOCAL_STORAGE",
                "to_name": "insertProductToDocLine",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['productListLineID']",
                        "target": "$['data']['queryParams']['productlistline_id']"
                    },
                    {
                        "source": "$['productrequestquantity']",
                        "target_transformation": function(value) {
                            return 0;
                        },
                        "target": "$['data']['queryParams']['req_qty']"
                    },
                    {
                        "source": "$['productscanquantity']",
                        "target_transformation": function(value) {
                            return 0;
                        },
                        "target": "$['data']['queryParams']['scan_qty']"
                    },
                    {
                        "source": "$['productbarcode']",
                        "target": "$['data']['queryParams']['barcode']"
                    },
                    {
                        "source": "$['docID']",
                        "target": "$['data']['queryParams']['document_id']"
                    },
                    {
                        "source": "$['productname']",
                        "target": "$['data']['queryParams']['product_name']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_getCurrentDoc_onsuccess_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "getCurrentDoc",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "newDocumentDetails",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['data']['name']",
                        "target": "$['docNameLabel:text']"
                    },
                    {
                        "source": "$['data']['document_time']",
                        "target": "$['docTimeLabel:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_getCurrentDoc_onbeforesend_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "getCurrentDoc",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['data']['id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_productQrCodeValidation_onsuccess_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['docID']"
                    }
                ]
            },
            {
                "from_name": "productQrCodeValidation",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body'][0]['id']",
                        "target": "$['productListLineID']"
                    },
                    {
                        "source": "$['body'][0]['barcode']",
                        "target": "$['productbarcode']"
                    },
                    {
                        "source": "$['body'][0]['product_name']",
                        "target": "$['productname']"
                    }
                ]
            },
            {
                "from_name": "productQrCodeValidation",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentMismatch",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body'][0]['id']",
                        "target_transformation": function(value) {
                            return value != undefined ? false : true;
                        },
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "productCode",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['productCode']"
                    }
                ]
            },
            {
                "from_name": "scannedValue",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['productQrCode']"
                    }
                ]
            },
            {
                "from_name": "scanQty",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['productscanquantity']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_productQrCodeValidation_onbeforesend_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "productQrCodeValidation",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['domainID']",
                        "target": "$['parameters']['domainID']"
                    }
                ]
            },
            {
                "from_name": "productCode",
                "from_type": "LOCAL_STORAGE",
                "to_name": "productQrCodeValidation",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['qrcode']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_insertProductToDocLineQR_onerror_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "productCode",
                "from_type": "LOCAL_STORAGE",
                "to_name": "newDocumentDetails",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target_transformation": function(value, element) {
                            return "Insert QR Error"
                        },
                        "target": "$['mobileheader:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_insertProductToDocLineQR_onsuccess_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "insertProductToDocLineQR",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body'][0]['id']",
                        "target": "$['doclineid']"
                    },
                    {
                        "source": "$['body'][0]['barcode']",
                        "target": "$['productbarcode']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_insertProductToDocLineQR_onbeforesend_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "insertProductToDocLineQR",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['id']",
                        "target_transformation": function(value) {
                            return 1;
                        },
                        "target": "$['parameters']['write_uid']"
                    }
                ]
            },
            {
                "from_name": "selectedDocumentDetails",
                "from_type": "LOCAL_STORAGE",
                "to_name": "insertProductToDocLineQR",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['productListLineID']",
                        "target": "$['parameters']['productlistline_id']"
                    },
                    {
                        "source": "$['productrequestquantity']",
                        "target_transformation": function(value) {
                            return 0;
                        },
                        "target": "$['parameters']['req_qty']"
                    },
                    {
                        "source": "$['productscanquantity']",
                        "target": "$['parameters']['scan_qty']"
                    },
                    {
                        "source": "$['docID']",
                        "target": "$['parameters']['document_id']"
                    },
                    {
                        "source": "$['productbarcode']",
                        "target": "$['parameters']['barcode']"
                    },
                    {
                        "source": "$['productname']",
                        "target": "$['parameters']['product_name']"
                    },
                    {
                        "source": "$['productQrCode']",
                        "target": "$['parameters']['qr_code']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_productValidation_onsuccess_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "productValidation",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['id']",
                        "target": "$['productListLineID']"
                    },
                    {
                        "source": "$['body']['barcode']",
                        "target": "$['productbarcode']"
                    },
                    {
                        "source": "$['body']['product_name']",
                        "target": "$['productname']"
                    }
                ]
            },
            {
                "from_name": "productValidation",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "documentMismatch",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['id']",
                        "target_transformation": function(value) {
                            return value != undefined ? false : true;
                        },
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['docID']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_productValidation_onbeforesend_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "productValidation",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['domainID']",
                        "target": "$['parameters']['domainID']"
                    }
                ]
            },
            {
                "from_name": "selectedDocumentDetails",
                "from_type": "LOCAL_STORAGE",
                "to_name": "productValidation",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['docID']",
                        "target": "$['parameters']['docID']"
                    }
                ]
            },
            {
                "from_name": "productCode",
                "from_type": "LOCAL_STORAGE",
                "to_name": "productValidation",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['productCode']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_getCurrentDoc_1_onsuccess_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "getCurrentDoc_1",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "newDocumentDetails",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body']['name']",
                        "target": "$['docNameLabel:text']"
                    },
                    {
                        "source": "$['body']['document_time']",
                        "target": "$['docTimeLabel:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentDetails_getCurrentDoc_1_onbeforesend_mapping_0"] = {
        "homeScreen": "newDocumentDetails",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "getCurrentDoc_1",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Api-Express-Api-Key": "{API_EXPRESS_API_KEY}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['id']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.currentDocDetailsGetService = Apperyio.datasources.currentDocDetailsGetService = new Apperyio.DataSource(eoDocsServiceDetailsGet, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_currentDocDetailsGetService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_currentDocDetailsGetService_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_currentDocDetailsGetService_onerror_mapping_0"]);
        }
    });
    window.submitDoc = Apperyio.datasources.submitDoc = new Apperyio.DataSource(eoDocsService_submitDoc_docID, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_submitDoc_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_submitDoc_onsuccess_mapping_0"]);
            Apperyio.navigateTo('mainPage', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.barcodeReadrToDocLineScan = Apperyio.datasources.barcodeReadrToDocLineScan = new Apperyio.DataSource(BarcodeService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_barcodeReadrToDocLineScan_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_barcodeReadrToDocLineScan_onsuccess_mapping_0"]);
            if (Apperyio.storage.documentMismatch.get() == true) {
                Apperyio.storage.scanModeOn.set(false)
                return;
            }
            var barcode = Apperyio.storage.scannedValue.get()
            if (barcode[0] == "[") {
                var temp = "";
                var i = 1;
                for (i; i < barcode.length; i++) {
                    if (barcode[i] != "]") {
                        temp += barcode[i]
                    } else {
                        Apperyio.storage.productCode.set(temp)
                        break;
                    }
                }
                if (barcode[++i] == "[") {
                    temp = "";
                    i++;
                    for (i; i < barcode.length; i++) {
                        if (barcode[i] != "]") {
                            temp += barcode[i]
                        } else {
                            Apperyio.storage.scanQty.set(temp)
                            break;
                        }
                    }
                }
                productQrCodeValidation.execute({});
            } else {
                productBarcodeValidation.execute({});
            }
            ;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.productBarcodeValidation = Apperyio.datasources.productBarcodeValidation = new Apperyio.DataSource(validateProductBarcode, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_productBarcodeValidation_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_productBarcodeValidation_onsuccess_mapping_0"]);
            if (Apperyio.storage.documentMismatch.get() == true) {
                Apperyio.navigateTo('scanProductDetailsNotFoundDialog', {
                    transition: 'pop'
                });
            } else {
                insertProductToDocLine.execute({});
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            try {
                $a.storage["scanModeOn"].update("$", "false")
            } catch (e) {
                console.error(e)
            };
            Apperyio.navigateTo('scanProductDetailsNotFoundDialog', {
                transition: 'pop'
            });
        }
    });
    window.insertProductToDocLine = Apperyio.datasources.insertProductToDocLine = new Apperyio.DataSource(insertDocLine, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_insertProductToDocLine_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_insertProductToDocLine_onsuccess_mapping_0"]);
            Apperyio.navigateTo('scanDocDetailsFoundDialog', {
                transition: 'pop'
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_insertProductToDocLine_onerror_mapping_0"]);
        }
    });
    window.getCurrentDoc = Apperyio.datasources.getCurrentDoc = new Apperyio.DataSource(eoDocsGeneratedService_get, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_getCurrentDoc_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_getCurrentDoc_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.productQrCodeValidation = Apperyio.datasources.productQrCodeValidation = new Apperyio.DataSource(eoStockScanAPI_eoDocsService_validateProductQrCode_get, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_productQrCodeValidation_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_productQrCodeValidation_onsuccess_mapping_0"]);
            if (Apperyio.storage.documentMismatch.get() == true) {
                Apperyio.navigateTo('scanProductDetailsNotFoundDialog', {
                    transition: 'pop'
                });
            } else {
                insertProductToDocLineQR.execute({});
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            Apperyio.navigateTo('scanProductDetailsNotFoundDialog', {
                transition: 'pop'
            });
        }
    });
    window.insertProductToDocLineQR = Apperyio.datasources.insertProductToDocLineQR = new Apperyio.DataSource(eoStockScanAPI_eoDocsService_insertDocLineQR_post, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_insertProductToDocLineQR_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_insertProductToDocLineQR_onsuccess_mapping_0"]);
            Apperyio.navigateTo('scanDocDetailsFoundDialog', {
                transition: 'pop'
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_insertProductToDocLineQR_onerror_mapping_0"]);
        }
    });
    window.productValidation = Apperyio.datasources.productValidation = new Apperyio.DataSource(eoStockScanAPI_eoDocsService_reqValidation_get, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_productValidation_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_productValidation_onsuccess_mapping_0"]);
            if (Apperyio.storage.documentMismatch.get() == true) {
                Apperyio.navigateTo('scanProductDetailsNotFoundDialog', {
                    transition: 'pop'
                });
            } else {
                insertProductToDocLine.execute({});
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.getCurrentDoc_1 = Apperyio.datasources.getCurrentDoc_1 = new Apperyio.DataSource(eoStockScanAPI_eoDocsService_getDoc_get, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_getCurrentDoc_1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_getCurrentDoc_1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'newDocumentDetails';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var newDocumentDetails_onLoad = function() {
        newDocumentDetails_elementsExtraJS();
        try {
            getCurrentDoc_1.execute({});
        } catch (e) {
            console.error(e);
            hideSpinner();
        };
        newDocumentDetails_deviceEvents();
        newDocumentDetails_windowEvents();
        newDocumentDetails_elementsEvents();
    };
    // screen window events
    function newDocumentDetails_windowEvents() {
        $('#newDocumentDetails').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#newDocumentDetails').on({
            pageshow: function(event) {
                if (Apperyio.storage.scanModeOn.get() == "true") {
                    barcodeReadrToDocLineScan.execute({});
                } else {};
                Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_newDocumentDetails_onpageshow_mapping_2"]);
            },
        });
    };
    // device events
    function newDocumentDetails_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    Apperyio.navigateTo('mainPage', {
                        reverse: false
                    });
                },
            });
        });
    };
    // screen elements extra js
    function newDocumentDetails_elementsExtraJS() {
        // screen (newDocumentDetails) extra code
        /* vizualizeDocPopup */
        $("#newDocumentDetails_vizualizeDocPopup").popup("option", "positionTo", "window");
        /* mobilelist_44 */
        listView = $("#newDocumentDetails_mobilelist_44");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#newDocumentDetails_mobilelist_44 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_45 */
        /* mobilecollapsblock_51 */
        $("#newDocumentDetails_mobilecollapsblock_51 .ui-collapsible-heading-toggle").attr("tabindex", "6");
        /* documentDetailsList */
        listView = $("#newDocumentDetails_documentDetailsList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#newDocumentDetails_documentDetailsList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* documentDetailsListItem */
        /* mobilecollapsblock_24 */
        $("#newDocumentDetails_mobilecollapsblock_24 .ui-collapsible-heading-toggle").attr("tabindex", "3");
    };
    // screen elements handler
    function newDocumentDetails_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#newDocumentDetails_vizualizeDocPopup [name="mobilelistitem_45"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('scanDocDetailsFoundDialog', {
                        transition: 'pop'
                    });
                }
            },
        }, '#newDocumentDetails_vizualizeDocPopup [name="mobilelistitem_45"]');
        $(document).off("change", '#newDocumentDetails_mobilecontainer [name="scanSearchBarNewDocDetails"]').on({
            change: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_scanSearchBarNewDocDetails_onchange_mapping_0"]);
                var barcode = Apperyio.storage.scannedValue.get();
                if (barcode[0] == "[") {
                    var temp = "";
                    var i = 1;
                    for (i; i < barcode.length; i++) {
                        if (barcode[i] != "]") {
                            temp += barcode[i]
                        } else {
                            Apperyio.storage.productCode.set(temp)
                            break;
                        }
                    }
                    if (barcode[++i] == "[") {
                        temp = "";
                        i++;
                        for (i; i < barcode.length; i++) {
                            if (barcode[i] != "]") {
                                temp += barcode[i]
                            } else {
                                Apperyio.storage.scanQty.set(temp)
                                break;
                            }
                        }
                    }
                    productQrCodeValidation.execute({});
                } else {
                    productBarcodeValidation.execute({});
                }
                ;
                Apperyio.processMappingAction(Apperyio.mappings["newDocumentDetails_scanSearchBarNewDocDetails_onchange_mapping_3"]);
            },
        }, '#newDocumentDetails_mobilecontainer [name="scanSearchBarNewDocDetails"]');
        $(document).off("click", '#newDocumentDetails_mobilecontainer [name="scanProductButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["scanModeOn"].update("$", "true")
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        barcodeReadrToDocLineScan.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#newDocumentDetails_mobilecontainer [name="scanProductButton"]');
        $(document).off("click", '#newDocumentDetails_mobilecontainer [name="submitDocumentButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        submitDoc.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#newDocumentDetails_mobilecontainer [name="submitDocumentButton"]');
        $(document).off("click", '#newDocumentDetails_mobilecontainer [name="vizualizeButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('newDocumentListDialog', {
                        transition: 'pop'
                    });
                }
            },
        }, '#newDocumentDetails_mobilecontainer [name="vizualizeButton"]');
        $(document).off("click", '#newDocumentDetails_mobilecontainer [name="documentDetailsListItem"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('scanDocDetailsFoundDialog', {
                        transition: 'pop'
                    });
                }
            },
        }, '#newDocumentDetails_mobilecontainer [name="documentDetailsListItem"]');
    };
    $(document).off("pagebeforeshow", "#newDocumentDetails").on("pagebeforeshow", "#newDocumentDetails", function(event, ui) {
        Apperyio.CurrentScreen = "newDocumentDetails";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    newDocumentDetails_onLoad();
};
$(document).off("pagecreate", "#newDocumentDetails").on("pagecreate", "#newDocumentDetails", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    newDocumentDetails_js();
});