/*
 * JS for newDocumentListDialog generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function newDocumentListDialog_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileworkarea_4': 'newDocumentListDialog_mobileworkarea_4',
        'eoLogo': 'newDocumentListDialog_eoLogo',
        'mobileworkarea_2': 'newDocumentListDialog_mobileworkarea_2',
        'mobilelist_5': 'newDocumentListDialog_mobilelist_5',
        'mobilelistitem_6': 'newDocumentListDialog_mobilelistitem_6',
        'mobilelistitembutton_7': 'newDocumentListDialog_mobilelistitembutton_7',
        'mobilecollapsblock_12': 'newDocumentListDialog_mobilecollapsblock_12',
        'mobilecollapsblockheader_13': 'newDocumentListDialog_mobilecollapsblockheader_13',
        'productNameLabel': 'newDocumentListDialog_productNameLabel',
        'mobilecollapsblockcontent_14': 'newDocumentListDialog_mobilecollapsblockcontent_14',
        'mobilegrid_16': 'newDocumentListDialog_mobilegrid_16',
        'mobilegridcell_17': 'newDocumentListDialog_mobilegridcell_17',
        'productBarcodeLabel': 'newDocumentListDialog_productBarcodeLabel',
        'mobilegridcell_18': 'newDocumentListDialog_mobilegridcell_18',
        'productBarcodeLabelShow': 'newDocumentListDialog_productBarcodeLabelShow',
        'mobilegridcell_19': 'newDocumentListDialog_mobilegridcell_19',
        'requestQuantityLabel': 'newDocumentListDialog_requestQuantityLabel',
        'mobilegridcell_20': 'newDocumentListDialog_mobilegridcell_20',
        'requestQuantityLabelShow': 'newDocumentListDialog_requestQuantityLabelShow',
        'mobilegridcell_21': 'newDocumentListDialog_mobilegridcell_21',
        'scanQuantityLabel': 'newDocumentListDialog_scanQuantityLabel',
        'mobilegridcell_22': 'newDocumentListDialog_mobilegridcell_22',
        'scanQuantityLabelShow': 'newDocumentListDialog_scanQuantityLabelShow',
        'mobilegridcell_23': 'newDocumentListDialog_mobilegridcell_23',
        'qrCodeLabel': 'newDocumentListDialog_qrCodeLabel',
        'mobilegridcell_24': 'newDocumentListDialog_mobilegridcell_24',
        'qrCodeLabelShow': 'newDocumentListDialog_qrCodeLabelShow',
        'mobileworkarea_3': 'newDocumentListDialog_mobileworkarea_3'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["newDocumentListDialog_getAllDocLines_onsuccess_mapping_0"] = {
        "homeScreen": "newDocumentListDialog",
        "directions": [
            {
                "from_name": "getAllDocLines",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "newDocumentListDialog",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['data']['response'][i]",
                        "target_transformation": function(value, element) {
                            element.on("click", function() {
                                Apperyio.storage.selectedDocumentDetails.set(value);
                                Apperyio.storage.editMode.set(true);
                                Apperyio.storage.inputQty.set(value.productscanquantity);
                            })
                        },
                        "target": "$['mobilelistitem_6']"
                    },
                    {
                        "source": "$['data']['response'][i]['productname']",
                        "target": "$['mobilelistitem_6']['productNameLabel:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productbarcode']",
                        "target": "$['mobilelistitem_6']['productBarcodeLabelShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != '0') ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['requestQuantityLabel:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target": "$['mobilelistitem_6']['requestQuantityLabelShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != '0') ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['requestQuantityLabelShow:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productscanquantity']",
                        "target": "$['mobilelistitem_6']['scanQuantityLabelShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['productscanquantity']",
                        "target_transformation": function(value, element) {
                            return value != null ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['scanQuantityLabelShow:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['qrcode']",
                        "target": "$['mobilelistitem_6']['qrCodeLabelShow:text']"
                    },
                    {
                        "source": "$['data']['response'][i]['qrcode']",
                        "target_transformation": function(value, element) {
                            return value != null ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['qrCodeLabel:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['qrcode']",
                        "target_transformation": function(value, element) {
                            return value != null ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['qrCodeLabelShow:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productbarcode']",
                        "target_transformation": function(value, element) {
                            return value != null ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['productBarcodeLabelShow:visible']"
                    },
                    {
                        "source": "$['data']['response'][i]['productbarcode']",
                        "target_transformation": function(value, element) {
                            return value != null ? true : false;
                        },
                        "target": "$['mobilelistitem_6']['productBarcodeLabel:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["newDocumentListDialog_getAllDocLines_onbeforesend_mapping_0"] = {
        "homeScreen": "newDocumentListDialog",
        "directions": [
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "getAllDocLines",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['data']['pathParams']['id']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.getAllDocLines = Apperyio.datasources.getAllDocLines = new Apperyio.DataSource(eoDocsServiceDetailsGet, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentListDialog_getAllDocLines_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["newDocumentListDialog_getAllDocLines_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'newDocumentListDialog';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var newDocumentListDialog_onLoad = function() {
        newDocumentListDialog_elementsExtraJS();
        newDocumentListDialog_deviceEvents();
        newDocumentListDialog_windowEvents();
        newDocumentListDialog_elementsEvents();
    };
    // screen window events
    function newDocumentListDialog_windowEvents() {
        $('#newDocumentListDialog').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#newDocumentListDialog').on({
            pageshow: function(event) {
                try {
                    getAllDocLines.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        });
    };
    // device events
    function newDocumentListDialog_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    Apperyio.navigateTo('newDocumentDetails', {
                        reverse: false
                    });
                },
            });
        });
    };
    // screen elements extra js
    function newDocumentListDialog_elementsExtraJS() {
        // screen (newDocumentListDialog) extra code
        /* mobilelist_5 */
        listView = $("#newDocumentListDialog_mobilelist_5");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#newDocumentListDialog_mobilelist_5 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_6 */
        /* mobilecollapsblock_12 */
        $("#newDocumentListDialog_mobilecollapsblock_12 .ui-collapsible-heading-toggle").attr("tabindex", "2");
    };
    // screen elements handler
    function newDocumentListDialog_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#newDocumentListDialog_mobilecontainer [name="mobilelistitem_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('scanDocDetailsFoundDialog_clone_1', {
                        transition: 'pop'
                    });
                }
            },
        }, '#newDocumentListDialog_mobilecontainer [name="mobilelistitem_6"]');
    };
    $(document).off("pagebeforeshow", "#newDocumentListDialog").on("pagebeforeshow", "#newDocumentListDialog", function(event, ui) {
        Apperyio.CurrentScreen = "newDocumentListDialog";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    newDocumentListDialog_onLoad();
};
$(document).off("pagecreate", "#newDocumentListDialog").on("pagecreate", "#newDocumentListDialog", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    newDocumentListDialog_js();
});