/*
 * JS for scanProductDetailsNotFoundDialog generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function scanProductDetailsNotFoundDialog_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'notFoundLabel': 'scanProductDetailsNotFoundDialog_notFoundLabel',
        'questionLabel': 'scanProductDetailsNotFoundDialog_questionLabel',
        'mobilegrid_4': 'scanProductDetailsNotFoundDialog_mobilegrid_4',
        'mobilegridcell_5': 'scanProductDetailsNotFoundDialog_mobilegridcell_5',
        'yesButton': 'scanProductDetailsNotFoundDialog_yesButton',
        'mobilegridcell_6': 'scanProductDetailsNotFoundDialog_mobilegridcell_6',
        'mobilegridcell_9': 'scanProductDetailsNotFoundDialog_mobilegridcell_9',
        'noButton': 'scanProductDetailsNotFoundDialog_noButton',
        'nameProductInput': 'scanProductDetailsNotFoundDialog_nameProductInput',
        'spacer_13': 'scanProductDetailsNotFoundDialog_spacer_13',
        'scanQTYLabel': 'scanProductDetailsNotFoundDialog_scanQTYLabel',
        'scanQTYInput': 'scanProductDetailsNotFoundDialog_scanQTYInput',
        'mobilegrid_14': 'scanProductDetailsNotFoundDialog_mobilegrid_14',
        'mobilegridcell_15': 'scanProductDetailsNotFoundDialog_mobilegridcell_15',
        'mobilegridcell_16': 'scanProductDetailsNotFoundDialog_mobilegridcell_16',
        'submitButton': 'scanProductDetailsNotFoundDialog_submitButton',
        'mobilegridcell_19': 'scanProductDetailsNotFoundDialog_mobilegridcell_19'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["scanProductDetailsNotFoundDialog_insertDoclineAnyway_onsuccess_mapping_0"] = {
        "homeScreen": "scanProductDetailsNotFoundDialog",
        "directions": []
    };
    Apperyio.mappings["scanProductDetailsNotFoundDialog_insertDoclineAnyway_onbeforesend_mapping_0"] = {
        "homeScreen": "scanProductDetailsNotFoundDialog",
        "directions": [
            {
                "from_name": "scanProductDetailsNotFoundDialog",
                "from_type": "UI",
                "to_name": "insertDoclineAnyway",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['scanQTYInput:text']",
                        "target": "$['data']['queryParams']['scan_qty']"
                    },
                    {
                        "source": "$['nameProductInput:text']",
                        "target": "$['data']['queryParams']['product_name']"
                    }
                ]
            },
            {
                "from_name": "selectedDocumentDetails",
                "from_type": "LOCAL_STORAGE",
                "to_name": "insertDoclineAnyway",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['productbarcode']",
                        "target": "$['data']['queryParams']['barcode']"
                    }
                ]
            },
            {
                "from_name": "selectedDocID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "insertDoclineAnyway",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['data']['queryParams']['docID']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.insertDoclineAnyway = Apperyio.datasources.insertDoclineAnyway = new Apperyio.DataSource(insertDocLineNoProductAvailable, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["scanProductDetailsNotFoundDialog_insertDoclineAnyway_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["scanProductDetailsNotFoundDialog_insertDoclineAnyway_onsuccess_mapping_0"]);
            closePopup();
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'scanProductDetailsNotFoundDialog';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var scanProductDetailsNotFoundDialog_onLoad = function() {
        scanProductDetailsNotFoundDialog_elementsExtraJS();
        scanProductDetailsNotFoundDialog_deviceEvents();
        scanProductDetailsNotFoundDialog_windowEvents();
        scanProductDetailsNotFoundDialog_elementsEvents();
    };
    // screen window events
    function scanProductDetailsNotFoundDialog_windowEvents() {
        $('#scanProductDetailsNotFoundDialog').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#scanProductDetailsNotFoundDialog').on({
            pageshow: function(event) {
                toggle('scanProductDetailsNotFoundDialog_mobilegrid_4', 'mob', 'true');
                toggle('scanProductDetailsNotFoundDialog_nameProductInput', 'mob', 'false');
                toggle('scanProductDetailsNotFoundDialog_notFoundLabel', 'mob', 'true');
                toggle('scanProductDetailsNotFoundDialog_questionLabel', 'mob', 'true');
                toggle('scanProductDetailsNotFoundDialog_scanQTYInput', 'mob', 'false');
                toggle('scanProductDetailsNotFoundDialog_scanQTYLabel', 'mob', 'false');
                toggle('scanProductDetailsNotFoundDialog_submitButton', 'mob', 'false');
            },
        });
    };
    // device events
    function scanProductDetailsNotFoundDialog_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    closePopup();
                },
            });
        });
    };
    // screen elements extra js
    function scanProductDetailsNotFoundDialog_elementsExtraJS() {
        // screen (scanProductDetailsNotFoundDialog) extra code
    };
    // screen elements handler
    function scanProductDetailsNotFoundDialog_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#scanProductDetailsNotFoundDialog_mobilecontainer [name="yesButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    toggle('scanProductDetailsNotFoundDialog_notFoundLabel', 'mob', 'false');
                    toggle('scanProductDetailsNotFoundDialog_questionLabel', 'mob', 'false');
                    toggle('scanProductDetailsNotFoundDialog_mobilegrid_4', 'mob', 'false');
                    toggle('scanProductDetailsNotFoundDialog_nameProductInput', 'mob', 'true');
                    toggle('scanProductDetailsNotFoundDialog_scanQTYLabel', 'mob', 'true');
                    toggle('scanProductDetailsNotFoundDialog_scanQTYInput', 'mob', 'true');
                    toggle('scanProductDetailsNotFoundDialog_submitButton', 'mob', 'true');
                }
            },
        }, '#scanProductDetailsNotFoundDialog_mobilecontainer [name="yesButton"]');
        $(document).off("click", '#scanProductDetailsNotFoundDialog_mobilecontainer [name="noButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    closePopup();
                }
            },
        }, '#scanProductDetailsNotFoundDialog_mobilecontainer [name="noButton"]');
        $(document).off("click", '#scanProductDetailsNotFoundDialog_mobilecontainer [name="submitButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        insertDoclineAnyway.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#scanProductDetailsNotFoundDialog_mobilecontainer [name="submitButton"]');
    };
    $(document).off("pagebeforeshow", "#scanProductDetailsNotFoundDialog").on("pagebeforeshow", "#scanProductDetailsNotFoundDialog", function(event, ui) {
        Apperyio.CurrentScreen = "scanProductDetailsNotFoundDialog";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    scanProductDetailsNotFoundDialog_onLoad();
};
$(document).off("pagecreate", "#scanProductDetailsNotFoundDialog").on("pagecreate", "#scanProductDetailsNotFoundDialog", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    scanProductDetailsNotFoundDialog_js();
});