/*
 * JS for scanDocDetailsNotFoundDialog_clone_1 generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function scanDocDetailsNotFoundDialog_clone_1_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'scanDocDetailsNotFoundDialog_clone_1_mobilelabel_2',
        'spacer_3': 'scanDocDetailsNotFoundDialog_clone_1_spacer_3',
        'mobilelabel_4': 'scanDocDetailsNotFoundDialog_clone_1_mobilelabel_4',
        'mobilegrid_5': 'scanDocDetailsNotFoundDialog_clone_1_mobilegrid_5',
        'mobilegridcell_6': 'scanDocDetailsNotFoundDialog_clone_1_mobilegridcell_6',
        'yesButton': 'scanDocDetailsNotFoundDialog_clone_1_yesButton',
        'mobilegridcell_7': 'scanDocDetailsNotFoundDialog_clone_1_mobilegridcell_7',
        'mobilegridcell_10': 'scanDocDetailsNotFoundDialog_clone_1_mobilegridcell_10',
        'noButton': 'scanDocDetailsNotFoundDialog_clone_1_noButton'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["scanDocDetailsNotFoundDialog_clone_1_insertIntoDocLine_onsuccess_mapping_0"] = {
        "homeScreen": "scanDocDetailsNotFoundDialog_clone_1",
        "directions": [
            {
                "from_name": "insertIntoDocLine",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['response'][0]['id']",
                        "target": "$['doclineid']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["scanDocDetailsNotFoundDialog_clone_1_insertIntoDocLine_onbeforesend_mapping_0"] = {
        "homeScreen": "scanDocDetailsNotFoundDialog_clone_1",
        "directions": [
            {
                "from_name": "selectedDocumentDetails",
                "from_type": "LOCAL_STORAGE",
                "to_name": "insertIntoDocLine",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['productListLineID']",
                        "target": "$['data']['queryParams']['productlistline_id']"
                    },
                    {
                        "source": "$['productbarcode']",
                        "target": "$['data']['queryParams']['barcode']"
                    },
                    {
                        "source": "$['docID']",
                        "target": "$['data']['queryParams']['document_id']"
                    },
                    {
                        "source": "$['productname']",
                        "target": "$['data']['queryParams']['product_name']"
                    }
                ]
            },
            {
                "to_name": "insertIntoDocLine",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "target_transformation": function(value) {
                            return 0;
                        },
                        "target": "$['data']['queryParams']['req_qty']"
                    },
                    {
                        "target_transformation": function(value) {
                            return 1;
                        },
                        "target": "$['data']['queryParams']['write_uid']"
                    },
                    {
                        "target_transformation": function(value) {
                            return 0;
                        },
                        "target": "$['data']['queryParams']['scan_qty']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.insertIntoDocLine = Apperyio.datasources.insertIntoDocLine = new Apperyio.DataSource(insertDocLine, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["scanDocDetailsNotFoundDialog_clone_1_insertIntoDocLine_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["scanDocDetailsNotFoundDialog_clone_1_insertIntoDocLine_onsuccess_mapping_0"]);
            Apperyio.navigateTo('scanDocDetailsFoundDialog_clone_1', {
                transition: 'pop'
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'scanDocDetailsNotFoundDialog_clone_1';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var scanDocDetailsNotFoundDialog_clone_1_onLoad = function() {
        scanDocDetailsNotFoundDialog_clone_1_elementsExtraJS();
        scanDocDetailsNotFoundDialog_clone_1_deviceEvents();
        scanDocDetailsNotFoundDialog_clone_1_windowEvents();
        scanDocDetailsNotFoundDialog_clone_1_elementsEvents();
    };
    // screen window events
    function scanDocDetailsNotFoundDialog_clone_1_windowEvents() {
        $('#scanDocDetailsNotFoundDialog_clone_1').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function scanDocDetailsNotFoundDialog_clone_1_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    closePopup();
                },
            });
        });
    };
    // screen elements extra js
    function scanDocDetailsNotFoundDialog_clone_1_elementsExtraJS() {
        // screen (scanDocDetailsNotFoundDialog_clone_1) extra code
    };
    // screen elements handler
    function scanDocDetailsNotFoundDialog_clone_1_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#scanDocDetailsNotFoundDialog_clone_1_mobilecontainer [name="yesButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        insertIntoDocLine.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#scanDocDetailsNotFoundDialog_clone_1_mobilecontainer [name="yesButton"]');
        $(document).off("click", '#scanDocDetailsNotFoundDialog_clone_1_mobilecontainer [name="noButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    closePopup();
                }
            },
        }, '#scanDocDetailsNotFoundDialog_clone_1_mobilecontainer [name="noButton"]');
    };
    $(document).off("pagebeforeshow", "#scanDocDetailsNotFoundDialog_clone_1").on("pagebeforeshow", "#scanDocDetailsNotFoundDialog_clone_1", function(event, ui) {
        Apperyio.CurrentScreen = "scanDocDetailsNotFoundDialog_clone_1";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    scanDocDetailsNotFoundDialog_clone_1_onLoad();
};
$(document).off("pagecreate", "#scanDocDetailsNotFoundDialog_clone_1").on("pagecreate", "#scanDocDetailsNotFoundDialog_clone_1", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    scanDocDetailsNotFoundDialog_clone_1_js();
});