/*
 * JS for scanDocDetailsNotFoundDialog generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function scanDocDetailsNotFoundDialog_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'scanDocDetailsNotFoundDialog_mobilelabel_2'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'scanDocDetailsNotFoundDialog';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var scanDocDetailsNotFoundDialog_onLoad = function() {
        scanDocDetailsNotFoundDialog_elementsExtraJS();
        scanDocDetailsNotFoundDialog_deviceEvents();
        scanDocDetailsNotFoundDialog_windowEvents();
        scanDocDetailsNotFoundDialog_elementsEvents();
    };
    // screen window events
    function scanDocDetailsNotFoundDialog_windowEvents() {
        $('#scanDocDetailsNotFoundDialog').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function scanDocDetailsNotFoundDialog_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    closePopup();
                },
            });
        });
    };
    // screen elements extra js
    function scanDocDetailsNotFoundDialog_elementsExtraJS() {
        // screen (scanDocDetailsNotFoundDialog) extra code
    };
    // screen elements handler
    function scanDocDetailsNotFoundDialog_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
    };
    $(document).off("pagebeforeshow", "#scanDocDetailsNotFoundDialog").on("pagebeforeshow", "#scanDocDetailsNotFoundDialog", function(event, ui) {
        Apperyio.CurrentScreen = "scanDocDetailsNotFoundDialog";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    scanDocDetailsNotFoundDialog_onLoad();
};
$(document).off("pagecreate", "#scanDocDetailsNotFoundDialog").on("pagecreate", "#scanDocDetailsNotFoundDialog", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    scanDocDetailsNotFoundDialog_js();
});