/*
 * JS for scanDocDetailsFoundDialog_clone_1 generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function scanDocDetailsFoundDialog_clone_1_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileworkarea_4': 'scanDocDetailsFoundDialog_clone_1_mobileworkarea_4',
        'eoLogo': 'scanDocDetailsFoundDialog_clone_1_eoLogo',
        'mobileworkarea_2': 'scanDocDetailsFoundDialog_clone_1_mobileworkarea_2',
        'productNameLabel': 'scanDocDetailsFoundDialog_clone_1_productNameLabel',
        'mobilegrid_5': 'scanDocDetailsFoundDialog_clone_1_mobilegrid_5',
        'mobilegridcell_6': 'scanDocDetailsFoundDialog_clone_1_mobilegridcell_6',
        'reqQuantityLabel': 'scanDocDetailsFoundDialog_clone_1_reqQuantityLabel',
        'mobilegridcell_7': 'scanDocDetailsFoundDialog_clone_1_mobilegridcell_7',
        'reqQuantityShowLabel': 'scanDocDetailsFoundDialog_clone_1_reqQuantityShowLabel',
        'spacer_12': 'scanDocDetailsFoundDialog_clone_1_spacer_12',
        'scannedQuantityInput': 'scanDocDetailsFoundDialog_clone_1_scannedQuantityInput',
        'okButton': 'scanDocDetailsFoundDialog_clone_1_okButton',
        'mobileworkarea_3': 'scanDocDetailsFoundDialog_clone_1_mobileworkarea_3'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["scanDocDetailsFoundDialog_clone_1_scanDocDetailsFoundDialog_clone_1_onpageshow_mapping_0"] = {
        "homeScreen": "scanDocDetailsFoundDialog_clone_1",
        "directions": [
            {
                "from_name": "selectedDocumentDetails",
                "from_type": "LOCAL_STORAGE",
                "to_name": "scanDocDetailsFoundDialog_clone_1",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['productname']",
                        "target": "$['productNameLabel:text']"
                    },
                    {
                        "source": "$['productrequestquantity']",
                        "target": "$['reqQuantityShowLabel:text']"
                    },
                    {
                        "source": "$['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 0) ? true : false;
                        },
                        "target": "$['reqQuantityShowLabel:visible']"
                    },
                    {
                        "source": "$['productrequestquantity']",
                        "target_transformation": function(value, element) {
                            return (value != null && value != 0) ? true : false;
                        },
                        "target": "$['reqQuantityLabel:visible']"
                    }
                ]
            },
            {
                "from_name": "inputQty",
                "from_type": "LOCAL_STORAGE",
                "to_name": "scanDocDetailsFoundDialog_clone_1",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target_transformation": function(value, element) {
                            if (value != null && Apperyio.storage.editMode.get()) {
                                return value;
                            }
                            return "";
                        },
                        "target": "$['scannedQuantityInput:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["scanDocDetailsFoundDialog_clone_1_okButton_onclick_mapping_0"] = {
        "homeScreen": "scanDocDetailsFoundDialog_clone_1",
        "directions": [
            {
                "from_name": "scanDocDetailsFoundDialog_clone_1",
                "from_type": "UI",
                "to_name": "selectedDocumentDetails",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['scannedQuantityInput:text']",
                        "target": "$['productscanquantity']"
                    }
                ]
            },
            {
                "from_name": "scanDocDetailsFoundDialog_clone_1",
                "from_type": "UI",
                "to_name": "inputQty",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['scannedQuantityInput:text']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["scanDocDetailsFoundDialog_clone_1_okValue_clone_1_onsuccess_mapping_0"] = {
        "homeScreen": "scanDocDetailsFoundDialog_clone_1",
        "directions": []
    };
    Apperyio.mappings["scanDocDetailsFoundDialog_clone_1_okValue_clone_1_onbeforesend_mapping_0"] = {
        "homeScreen": "scanDocDetailsFoundDialog_clone_1",
        "directions": [
            {
                "from_name": "scanDocDetailsFoundDialog_clone_1",
                "from_type": "UI",
                "to_name": "okValue_clone_1",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['scannedQuantityInput:text']",
                        "target": "$['data']['pathParams']['scannedQTY']"
                    }
                ]
            },
            {
                "from_name": "selectedDocumentDetails",
                "from_type": "LOCAL_STORAGE",
                "to_name": "okValue_clone_1",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "cached": false
                    }
                },
                "mappings": [
                    {
                        "source": "$['doclineid']",
                        "target": "$['data']['pathParams']['doclineID']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.okValue_clone_1 = Apperyio.datasources.okValue_clone_1 = new Apperyio.DataSource(eoDocsServiceSubmitScannedValue, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["scanDocDetailsFoundDialog_clone_1_okValue_clone_1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["scanDocDetailsFoundDialog_clone_1_okValue_clone_1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'scanDocDetailsFoundDialog_clone_1';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var scanDocDetailsFoundDialog_clone_1_onLoad = function() {
        scanDocDetailsFoundDialog_clone_1_elementsExtraJS();
        scanDocDetailsFoundDialog_clone_1_deviceEvents();
        scanDocDetailsFoundDialog_clone_1_windowEvents();
        scanDocDetailsFoundDialog_clone_1_elementsEvents();
    };
    // screen window events
    function scanDocDetailsFoundDialog_clone_1_windowEvents() {
        $('#scanDocDetailsFoundDialog_clone_1').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#scanDocDetailsFoundDialog_clone_1').on({
            pageshow: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["scanDocDetailsFoundDialog_clone_1_scanDocDetailsFoundDialog_clone_1_onpageshow_mapping_0"]);
            },
        });
    };
    // device events
    function scanDocDetailsFoundDialog_clone_1_deviceEvents() {
        document.addEventListener("deviceready", function() {
            $(document).off('backbutton ').on({
                "backbutton": function(event) {
                    closePopup();
                },
            });
        });
    };
    // screen elements extra js
    function scanDocDetailsFoundDialog_clone_1_elementsExtraJS() {
        // screen (scanDocDetailsFoundDialog_clone_1) extra code
    };
    // screen elements handler
    function scanDocDetailsFoundDialog_clone_1_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#scanDocDetailsFoundDialog_clone_1_mobilecontainer [name="okButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.processMappingAction(Apperyio.mappings["scanDocDetailsFoundDialog_clone_1_okButton_onclick_mapping_0"]);
                    if (Apperyio.storage.inputQty.get() != "") {
                        okValue_clone_1.execute({});
                        closePopup();
                    };
                }
            },
        }, '#scanDocDetailsFoundDialog_clone_1_mobilecontainer [name="okButton"]');
    };
    $(document).off("pagebeforeshow", "#scanDocDetailsFoundDialog_clone_1").on("pagebeforeshow", "#scanDocDetailsFoundDialog_clone_1", function(event, ui) {
        Apperyio.CurrentScreen = "scanDocDetailsFoundDialog_clone_1";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    scanDocDetailsFoundDialog_clone_1_onLoad();
};
$(document).off("pagecreate", "#scanDocDetailsFoundDialog_clone_1").on("pagecreate", "#scanDocDetailsFoundDialog_clone_1", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    scanDocDetailsFoundDialog_clone_1_js();
});