/*
 * JS for settingsDialog generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'cdeeb05f-dbd0-4b0f-a5dd-b1c2b9ac084c';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "loginPage",
    "location": "loginPage.html"
}, {
    "name": "newDocumentDetails",
    "location": "newDocumentDetails.html"
}, {
    "name": "loginSuccess",
    "location": "loginSuccess.html"
}, {
    "name": "loginFailed",
    "location": "loginFailed.html"
}, {
    "name": "createNewDocumentDialog",
    "location": "createNewDocumentDialog.html"
}, {
    "name": "settingsDialog",
    "location": "settingsDialog.html"
}, {
    "name": "documentListDialog",
    "location": "documentListDialog.html"
}, {
    "name": "newDocumentListDialog",
    "location": "newDocumentListDialog.html"
}, {
    "name": "scanDocDetailsNotFoundDialog_clone_1",
    "location": "scanDocDetailsNotFoundDialog_clone_1.html"
}, {
    "name": "areYouSure",
    "location": "areYouSure.html"
}, {
    "name": "scanDocDetailsNotFoundDialog",
    "location": "scanDocDetailsNotFoundDialog.html"
}, {
    "name": "scanDocDetailsFoundDialog_clone_1",
    "location": "scanDocDetailsFoundDialog_clone_1.html"
}, {
    "name": "documentListPage",
    "location": "documentListPage.html"
}, {
    "name": "listDocuments",
    "location": "listDocuments.html"
}, {
    "name": "mainPage",
    "location": "mainPage.html"
}, {
    "name": "scanDocDetailsFoundDialog",
    "location": "scanDocDetailsFoundDialog.html"
}, {
    "name": "documentDetails",
    "location": "documentDetails.html"
}, {
    "name": "scanProductDetailsNotFoundDialog",
    "location": "scanProductDetailsNotFoundDialog.html"
}];

function settingsDialog_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileworkarea_4': 'settingsDialog_mobileworkarea_4',
        'eoLogo': 'settingsDialog_eoLogo',
        'mobileworkarea_2': 'settingsDialog_mobileworkarea_2',
        'mobilegrid_5': 'settingsDialog_mobilegrid_5',
        'mobilegridcell_6': 'settingsDialog_mobilegridcell_6',
        'mobilelabel_10': 'settingsDialog_mobilelabel_10',
        'mobilegridcell_7': 'settingsDialog_mobilegridcell_7',
        'readRToggle': 'settingsDialog_readRToggle',
        'mobileworkarea_3': 'settingsDialog_mobileworkarea_3'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["settingsDialog_settingsDialog_onpageshow_mapping_0"] = {
        "homeScreen": "settingsDialog",
        "directions": [
            {
                "from_name": "userInfos",
                "from_type": "LOCAL_STORAGE",
                "to_name": "settingsDialog",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['scanWithScanner']",
                        "target": "$['readRToggle:toggled']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["settingsDialog_readRToggle_onchange_mapping_0"] = {
        "homeScreen": "settingsDialog",
        "directions": [
            {
                "from_name": "settingsDialog",
                "from_type": "UI",
                "to_name": "enteredUserInfos",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['readRToggle:toggled']",
                        "target": "$['scanWithScanner']"
                    }
                ]
            },
            {
                "from_name": "settingsDialog",
                "from_type": "UI",
                "to_name": "userInfos",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['readRToggle:toggled']",
                        "target": "$['scanWithScanner']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'settingsDialog';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var settingsDialog_onLoad = function() {
        settingsDialog_elementsExtraJS();
        settingsDialog_deviceEvents();
        settingsDialog_windowEvents();
        settingsDialog_elementsEvents();
    };
    // screen window events
    function settingsDialog_windowEvents() {
        $('#settingsDialog').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#settingsDialog').on({
            pageshow: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["settingsDialog_settingsDialog_onpageshow_mapping_0"]);
            },
        });
    };
    // device events
    function settingsDialog_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function settingsDialog_elementsExtraJS() {
        // screen (settingsDialog) extra code
        /* readRToggle */
        $("#settingsDialog_readRToggle").parent().find(".ui-flipswitch-on").attr("tabindex", "1");
    };
    // screen elements handler
    function settingsDialog_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("change", '#settingsDialog_mobilecontainer [name="readRToggle"]').on({
            change: function(event) {
                Apperyio.processMappingAction(Apperyio.mappings["settingsDialog_readRToggle_onchange_mapping_0"]);
            },
        }, '#settingsDialog_mobilecontainer [name="readRToggle"]');
    };
    $(document).off("pagebeforeshow", "#settingsDialog").on("pagebeforeshow", "#settingsDialog", function(event, ui) {
        Apperyio.CurrentScreen = "settingsDialog";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    settingsDialog_onLoad();
};
$(document).off("pagecreate", "#settingsDialog").on("pagecreate", "#settingsDialog", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    settingsDialog_js();
});